import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const ast: Topic = {
  id: "ast",
  code: "AST",
  number: 11,
  title: "Astrophysics",
  subject: "Physics",
  icon: "🌌",
  color: "#7c3aed",
  intro: "The physics of the cosmos. Orbits and gravity, the life cycle of stars, redshift and the Big Bang.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "The physics of the cosmos. Orbits and gravity, the life cycle of stars, redshift and the Big Bang.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Astrophysics", definition: "The physics of the cosmos. Orbits and gravity, the life cycle of stars, redshift and the Big Bang." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "ast-mcq-q01",
        question: "Placeholder question for Astrophysics — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "ast-qa-q01",
        question: "Placeholder exam question for Astrophysics. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
