import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const ce: Topic = {
  id: "ce",
  code: "CE",
  number: 4,
  title: "Current Electricity",
  subject: "Physics",
  icon: "⚡",
  color: "#f59e0b",
  intro: "Charge on the move. Current, voltage, resistance, series and parallel circuits, and how to keep electricity safe.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "Charge on the move. Current, voltage, resistance, series and parallel circuits, and how to keep electricity safe.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Current Electricity", definition: "Charge on the move. Current, voltage, resistance, series and parallel circuits, and how to keep electricity safe." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "ce-mcq-q01",
        question: "Placeholder question for Current Electricity — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "ce-qa-q01",
        question: "Placeholder exam question for Current Electricity. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
