import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const em: Topic = {
  id: "em",
  code: "EM",
  number: 9,
  title: "Electromagnetism",
  subject: "Physics",
  icon: "🧲",
  color: "#ec4899",
  intro: "Magnetism and electricity are two sides of one coin. Magnetic fields, the motor effect, generators and transformers.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "Magnetism and electricity are two sides of one coin. Magnetic fields, the motor effect, generators and transformers.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Electromagnetism", definition: "Magnetism and electricity are two sides of one coin. Magnetic fields, the motor effect, generators and transformers." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "em-mcq-q01",
        question: "Placeholder question for Electromagnetism — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "em-qa-q01",
        question: "Placeholder exam question for Electromagnetism. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
