import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const fm: Topic = {
  id: "fm",
  code: "FM",
  number: 3,
  title: "Forces and Motion",
  subject: "Physics",
  icon: "🚀",
  color: "#6366f1",
  intro: "How and why things move. Speed, velocity, acceleration, Newton's laws, momentum and the maths of motion graphs.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "How and why things move. Speed, velocity, acceleration, Newton's laws, momentum and the maths of motion graphs.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Forces and Motion", definition: "How and why things move. Speed, velocity, acceleration, Newton's laws, momentum and the maths of motion graphs." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "fm-mcq-q01",
        question: "Placeholder question for Forces and Motion — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "fm-qa-q01",
        question: "Placeholder exam question for Forces and Motion. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
