import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const fs: Topic = {
  id: "fs",
  code: "FS",
  number: 6,
  title: "Forces and Shape",
  subject: "Physics",
  icon: "🪝",
  color: "#84cc16",
  intro: "What forces do to objects: stretching, squashing and turning. Hooke's law, elastic behaviour, moments and equilibrium.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "What forces do to objects: stretching, squashing and turning. Hooke's law, elastic behaviour, moments and equilibrium.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Forces and Shape", definition: "What forces do to objects: stretching, squashing and turning. Hooke's law, elastic behaviour, moments and equilibrium." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "fs-mcq-q01",
        question: "Placeholder question for Forces and Shape — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "fs-qa-q01",
        question: "Placeholder exam question for Forces and Shape. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
