import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const ge: Topic = {
  id: "ge",
  code: "GE",
  number: 10,
  title: "Generating Electricity",
  subject: "Physics",
  icon: "🔌",
  color: "#14b8a6",
  intro: "Where our energy comes from. Renewable and non-renewable resources, power stations and the National Grid.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "Where our energy comes from. Renewable and non-renewable resources, power stations and the National Grid.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Generating Electricity", definition: "Where our energy comes from. Renewable and non-renewable resources, power stations and the National Grid." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "ge-mcq-q01",
        question: "Placeholder question for Generating Electricity — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "ge-qa-q01",
        question: "Placeholder exam question for Generating Electricity. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
