import type { Topic } from "../types";

// Topic 10 — Generating Electricity (Edexcel IGCSE Physics 4PH1).
// Energy resources (renewable & non-renewable), thermal power stations,
// the National Grid, and the I²R argument for high-voltage transmission.

export const ge: Topic = {
  id: "ge",
  code: "GE",
  number: 10,
  title: "Generating Electricity",
  subject: "Physics",
  icon: "🔌",
  color: "#14b8a6",
  intro:
    "Almost every appliance you use is powered by electricity generated somewhere else and delivered to you. In this topic you'll compare the energy resources we use to make it — renewables like wind, solar, hydroelectric, tidal, wave, geothermal and biomass, and non-renewables like coal, oil, gas and nuclear — weigh up their costs, reliability and environmental impact, see how a thermal power station turns fuel into electricity, and discover why the National Grid sends power across the country at extremely high voltage to avoid wasting energy in the cables.",
  guide: [
    {
      heading: "Renewable vs non-renewable resources",
      discovery: {
        problem:
          "Every second, the UK draws tens of gigawatts of electrical power. Some of the resources we use to make it (like coal) took millions of years to form and can never be replaced in a human lifetime; others (like the wind) arrive free every day. How should we sort our energy resources — and does it matter which kind we use?",
        idea: "Split resources into two groups by how fast nature replaces them. A **renewable** resource is replenished as fast as (or faster than) we use it, so it will not run out. A **non-renewable** resource is used up far faster than it forms, so the supply is finite and shrinking.",
      },
      body:
        "An **energy resource** is something we extract useful energy from to generate electricity (or to heat and move things).\n\n- **Renewable resources** are replaced as quickly as they are used, so they never run out on a human timescale: **solar, wind, hydroelectric, tidal, wave, geothermal** and **biomass**.\n- **Non-renewable resources** are used up much faster than they form, so the supply is finite: the **fossil fuels** (**coal, oil, natural gas**) and **nuclear** fuel (uranium).\n\nFossil fuels formed over millions of years from the remains of dead plants and animals. When we burn them they release the chemical energy stored inside, but they also release **carbon dioxide (CO₂)** — a greenhouse gas linked to climate change — plus other pollutants such as sulfur dioxide (which causes acid rain).\n\nNuclear fuel is not burned: energy is released by **nuclear fission** of uranium nuclei, which produces no CO₂ but does produce **radioactive waste** that stays dangerous for thousands of years.",
      diagrams: [
        {
          caption: "Sorting the main energy resources into renewable and non-renewable.",
          svg:
            '<svg viewBox="0 0 360 170" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two columns sorting energy resources into renewable and non-renewable">\n<rect x="8" y="8" width="166" height="154" rx="6" fill="#ecfdf5" stroke="#059669"/>\n<rect x="186" y="8" width="166" height="154" rx="6" fill="#fef2f2" stroke="#dc2626"/>\n<text x="91" y="28" font-size="13" font-weight="bold" text-anchor="middle" fill="#047857">RENEWABLE</text>\n<text x="269" y="28" font-size="13" font-weight="bold" text-anchor="middle" fill="#b91c1c">NON-RENEWABLE</text>\n<text x="91" y="50" font-size="11" text-anchor="middle" fill="#064e3b">Solar</text>\n<text x="91" y="66" font-size="11" text-anchor="middle" fill="#064e3b">Wind</text>\n<text x="91" y="82" font-size="11" text-anchor="middle" fill="#064e3b">Hydroelectric</text>\n<text x="91" y="98" font-size="11" text-anchor="middle" fill="#064e3b">Tidal</text>\n<text x="91" y="114" font-size="11" text-anchor="middle" fill="#064e3b">Wave</text>\n<text x="91" y="130" font-size="11" text-anchor="middle" fill="#064e3b">Geothermal</text>\n<text x="91" y="146" font-size="11" text-anchor="middle" fill="#064e3b">Biomass</text>\n<text x="269" y="58" font-size="11" text-anchor="middle" fill="#7f1d1d">Coal</text>\n<text x="269" y="78" font-size="11" text-anchor="middle" fill="#7f1d1d">Oil</text>\n<text x="269" y="98" font-size="11" text-anchor="middle" fill="#7f1d1d">Natural gas</text>\n<text x="269" y="124" font-size="10" text-anchor="middle" fill="#991b1b">(fossil fuels)</text>\n<text x="269" y="146" font-size="11" text-anchor="middle" fill="#7f1d1d">Nuclear (uranium)</text>\n</svg>',
        },
      ],
      keyPoints: [
        "Renewable = replaced as fast as it is used → will not run out.",
        "Non-renewable = used far faster than it forms → finite supply.",
        "Fossil fuels (coal, oil, gas) and nuclear are non-renewable.",
        "Burning fossil fuels releases CO₂; nuclear produces radioactive waste, not CO₂.",
      ],
      whyItWorks:
        "The label depends only on the rate of replacement compared with the rate of use. Sunlight, wind and tides are driven by the Sun and Moon and arrive continuously, so using them does not deplete them; fossil and nuclear fuels exist as a fixed stock that shrinks every time we use some.",
      strategies: ["Sort into two groups first", "Always ask: how fast is it replaced?"],
    },
    {
      heading: "How a thermal power station works",
      body:
        "Most coal, oil, gas, biomass and nuclear stations are **thermal** stations: they all work the same way, differing only in how they produce the heat.\n\nThe energy chain is:\n\n1. **Fuel** is burned (or, for nuclear, undergoes fission) to release **thermal energy** in the **boiler**.\n2. The thermal energy heats water to make high-pressure **steam**.\n3. The steam rushes past the blades of a **turbine**, making it spin (thermal → kinetic energy).\n4. The spinning turbine drives a **generator**, which produces **electricity** (kinetic → electrical energy).\n5. Used steam is cooled back to water in a **condenser** and recycled.\n\nThe useful output is electrical energy; the rest is mostly wasted as thermal energy in the cooling towers and exhaust, which is why thermal stations are typically only **30–40% efficient**.",
      diagrams: [
        {
          caption: "Energy flow through a thermal power station: fuel → boiler → turbine → generator.",
          svg:
            '<svg viewBox="0 0 420 120" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Flow chart of a thermal power station from fuel and boiler to turbine and generator producing electricity">\n<rect x="6" y="40" width="70" height="40" rx="5" fill="#fde68a" stroke="#b45309"/>\n<text x="41" y="58" font-size="10" text-anchor="middle" fill="#78350f">Fuel +</text>\n<text x="41" y="71" font-size="10" text-anchor="middle" fill="#78350f">boiler</text>\n<rect x="116" y="40" width="70" height="40" rx="5" fill="#bfdbfe" stroke="#1d4ed8"/>\n<text x="151" y="64" font-size="10" text-anchor="middle" fill="#1e3a8a">Steam</text>\n<rect x="226" y="40" width="70" height="40" rx="5" fill="#e2e8f0" stroke="#475569"/>\n<text x="261" y="64" font-size="10" text-anchor="middle" fill="#1e293b">Turbine</text>\n<rect x="336" y="40" width="78" height="40" rx="5" fill="#bbf7d0" stroke="#15803d"/>\n<text x="375" y="58" font-size="10" text-anchor="middle" fill="#14532d">Generator</text>\n<text x="375" y="71" font-size="9" text-anchor="middle" fill="#14532d">electricity</text>\n<defs><marker id="ar" markerWidth="9" markerHeight="9" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#334155"/></marker></defs>\n<path d="M76 60 H114" stroke="#334155" stroke-width="2" marker-end="url(#ar)"/>\n<path d="M186 60 H224" stroke="#334155" stroke-width="2" marker-end="url(#ar)"/>\n<path d="M296 60 H334" stroke="#334155" stroke-width="2" marker-end="url(#ar)"/>\n<text x="151" y="30" font-size="9" text-anchor="middle" fill="#64748b">thermal</text>\n<text x="261" y="30" font-size="9" text-anchor="middle" fill="#64748b">kinetic</text>\n<text x="375" y="30" font-size="9" text-anchor="middle" fill="#64748b">electrical</text>\n</svg>',
        },
      ],
      keyPoints: [
        "Fuel → boiler → steam → turbine → generator → electricity.",
        "Energy transfers: chemical/nuclear → thermal → kinetic → electrical.",
        "Coal, oil, gas, biomass and nuclear all use this same basic design.",
        "Typically only 30–40% efficient; most energy is wasted as heat.",
      ],
      whyItWorks:
        "A generator only makes electricity when something turns it. The whole point of the boiler, steam and turbine is to convert the fuel's stored energy into rotational kinetic energy that can spin the generator.",
      formulae: ["efficiency = (useful energy output ÷ total energy input) × 100%", "P = E / t"],
      strategies: ["Follow the energy through each stage", "Name the energy transfer at every arrow"],
    },
    {
      heading: "Non-renewable resources: fossil fuels and nuclear",
      body:
        "**Fossil fuels (coal, oil, natural gas)**\n\n- *Advantages:* reliable (work day and night, in any weather), high energy output, relatively cheap to build, fuel is easy to transport and store, can be switched on quickly to meet demand (especially gas).\n- *Disadvantages:* release **CO₂** (greenhouse gas → climate change) and other pollutants; coal and oil produce **sulfur dioxide** → acid rain; supplies are **finite** and will run out; prices can be volatile.\n\n**Nuclear (uranium)**\n\n- *Advantages:* very high energy output from a tiny amount of fuel; **no CO₂** during generation; reliable base-load supply.\n- *Disadvantages:* produces dangerous **radioactive waste** needing safe storage for thousands of years; very **high set-up and decommissioning costs**; small but serious risk of an accident; **long build time**.",
      keyPoints: [
        "Fossil fuels: reliable and cheap to build, but emit CO₂ and run out.",
        "Gas stations can start up quickly to meet peaks in demand.",
        "Nuclear: huge output, no CO₂, but radioactive waste and high cost.",
        "All non-renewables eventually run out (finite supply).",
      ],
      thinkDeeper:
        "Nuclear produces no CO₂ while running, yet it is non-renewable and controversial. Is 'low-carbon' the same as 'renewable'? (No — nuclear is low-carbon but still relies on a finite fuel and creates long-lived waste.)",
      strategies: ["Separate cost, reliability and environment", "Don't confuse 'low-carbon' with 'renewable'"],
    },
    {
      heading: "Renewable resources compared",
      body:
        "Each renewable resource taps a continuous natural flow of energy. Here is **how each one is used to generate electricity**, with its main pros and cons.\n\n**Solar** – *Photovoltaic (PV) cells* convert sunlight **directly** into electricity (no turbine or generator needed). Separately, *solar (thermal) heating panels* use the Sun's energy to heat water for buildings, and large *concentrated solar* plants use mirrors to make steam that drives a turbine. No fuel and no CO₂, but **unreliable** (no output at night, less on cloudy days) and high set-up cost. Best in sunny climates.\n\n**Wind** – Moving air pushes the blades of a turbine, which turns a generator (kinetic → electrical). No fuel or CO₂, low running cost, but **intermittent** (no wind, no power; too strong a wind and turbines shut down for safety). Some find turbines noisy or a blot on the landscape, and they take up large areas.\n\n**Hydroelectric (HEP)** – Water stored behind a dam is released and falls, spinning turbines that drive generators (gravitational store → kinetic → electrical). Reliable, very fast to switch on, no CO₂ and low running cost — but needs a suitable hilly/rainy valley, has a very high build cost, and flooding the reservoir destroys habitats and may displace people.\n\n**Tidal** – A *barrage* (dam) across an estuary traps water as the tide rises, then releases it through turbines as the tide falls. Tides are **very predictable**, and there is no fuel or CO₂, but barrages are expensive and can damage estuary habitats and shipping. Output still varies through the tidal cycle.\n\n**Wave** – Floating or shoreline devices are rocked by the up-and-down motion of surface waves; this movement drives a generator. Useful for island and coastal sites, but currently **small-scale**, costly, and produce little in calm seas — and devices must survive storms.\n\n**Geothermal** – In volcanic areas, water is pumped down to hot rocks underground; it returns as steam that drives a turbine and generator. **Reliable** and clean, but only practical where hot rocks are near the surface (e.g. Iceland, New Zealand).\n\n**Biomass and biofuels** – *Biomass* is plant material (wood, crops) or animal/food waste that is burned to heat water, exactly like a fossil-fuel thermal station; *biofuels* are liquid or gas fuels (e.g. bioethanol, biogas) made from these materials. They are considered roughly **carbon-neutral** because the plants absorb CO₂ as they grow, balancing the CO₂ released when burned. They are renewable (crops regrow) and use waste, but burning still releases CO₂ and other pollutants, growing the crops needs large areas of land that could be used for food, and supply takes time to grow.\n\nMost renewables share the same trade-off: **no fuel cost and little/no CO₂, but often unreliable, location-specific, and high set-up cost**. Biomass and geothermal are the exceptions on reliability.",
      diagrams: [
        {
          caption: "Rough comparison of resources by reliability and CO₂ emissions (taller bar = higher).",
          svg:
            '<svg viewBox="0 0 380 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Bar chart comparing reliability and carbon dioxide emissions for coal, nuclear, wind and hydroelectric">\n<line x1="40" y1="140" x2="370" y2="140" stroke="#475569" stroke-width="1.5"/>\n<line x1="40" y1="20" x2="40" y2="140" stroke="#475569" stroke-width="1.5"/>\n<rect x="60" y="40" width="22" height="100" fill="#64748b"/>\n<rect x="86" y="55" width="22" height="85" fill="#dc2626"/>\n<rect x="150" y="35" width="22" height="105" fill="#64748b"/>\n<rect x="176" y="125" width="22" height="15" fill="#dc2626"/>\n<rect x="240" y="100" width="22" height="40" fill="#64748b"/>\n<rect x="266" y="132" width="22" height="8" fill="#dc2626"/>\n<rect x="320" y="50" width="22" height="90" fill="#64748b"/>\n<rect x="346" y="130" width="22" height="10" fill="#dc2626"/>\n<text x="84" y="155" font-size="10" text-anchor="middle" fill="#1e293b">Coal</text>\n<text x="174" y="155" font-size="10" text-anchor="middle" fill="#1e293b">Nuclear</text>\n<text x="264" y="155" font-size="10" text-anchor="middle" fill="#1e293b">Wind</text>\n<text x="344" y="155" font-size="10" text-anchor="middle" fill="#1e293b">HEP</text>\n<rect x="120" y="166" width="12" height="9" fill="#64748b"/>\n<text x="138" y="174" font-size="9" fill="#334155">reliability</text>\n<rect x="210" y="166" width="12" height="9" fill="#dc2626"/>\n<text x="228" y="174" font-size="9" fill="#334155">CO2 emissions</text>\n</svg>',
        },
      ],
      keyPoints: [
        "Renewables: no fuel cost, little or no CO₂.",
        "Solar, wind and wave are unreliable (depend on weather).",
        "HEP, tidal and geothermal are reliable but need specific locations.",
        "Biomass is roughly carbon-neutral but still emits CO₂ when burned.",
      ],
      whyItWorks:
        "Renewables ultimately tap continuous natural flows (sunlight, the Sun-driven wind and water cycle, the Moon's tides, Earth's internal heat) rather than a stored chemical fuel, so there is nothing to burn and nothing to run out.",
      strategies: ["Group by reliability (steady vs weather-dependent)", "Match the resource to the location"],
    },
    {
      heading: "Choosing the right resource for a situation",
      discovery: {
        problem:
          "A remote island with strong winds, no fossil-fuel supply and no connection to a national grid needs electricity. A huge city needs a constant, reliable supply day and night. Should both use the same resource?",
        idea: "There is no single 'best' resource — the right choice depends on the situation. Compare resources against the factors that matter most for that case: cost, reliability, set-up time, location/availability and environmental impact.",
      },
      body:
        "To compare resources sensibly, weigh up several factors:\n\n- **Cost** — set-up (capital) cost vs running (fuel) cost.\n- **Reliability** — does it produce power on demand, or only when the weather/tide allows?\n- **Set-up time** — a gas station can be built in a year or two; a nuclear or hydro scheme takes many years.\n- **Availability / location** — geothermal needs hot rocks; HEP needs a valley; solar needs sunshine.\n- **Environmental impact** — CO₂ and other emissions, land use, habitat damage, waste.\n\n*Worked example — the remote, windy island:* with no grid connection and no fuel delivery, fuel-based stations are impractical. Strong, frequent wind makes **wind power** a strong choice; the unreliability of wind can be covered by storing energy in batteries or pairing it with solar. A large city, by contrast, needs guaranteed base-load power, so a mix including **nuclear or gas** for reliability plus renewables is more suitable.",
      keyPoints: [
        "No resource is best in every situation — it depends on the factors.",
        "Key factors: cost, reliability, set-up time, location, environment.",
        "Remote off-grid sites favour local renewables (e.g. wind/solar).",
        "Cities need reliable base-load power, often nuclear or gas in the mix.",
      ],
      strategies: ["List the factors, then score each option", "Identify the deciding factor for the situation"],
    },
    {
      heading: "Climate change and the move towards renewables",
      body:
        "For most of the 20th century, electricity came mainly from burning **fossil fuels**, because they are reliable, give a high output and were cheap to build. The problem is that burning them releases **carbon dioxide (CO₂)** and other **greenhouse gases**, which trap heat in the atmosphere and drive **global warming** and **climate change** (rising sea levels, more extreme weather).\n\nBecause of this, the **current trend is a shift away from fossil fuels towards low-carbon and renewable resources**:\n\n- Many countries are building large numbers of **wind farms** (on land and offshore) and **solar farms**.\n- Coal stations are being closed; gas is often used as a 'bridge' because it emits less CO₂ than coal per unit of energy.\n- **Nuclear** is used by some countries as a low-carbon (but non-renewable) part of the mix.\n- The cost of wind and solar has fallen sharply, making renewables increasingly competitive with fossil fuels.\n\nThe main challenge is that the most scalable renewables (wind, solar) are **intermittent**, so a low-carbon grid also needs **energy storage** (batteries, pumped-storage HEP) and reliable backup or 'firm' low-carbon sources to keep supply matched to demand.",
      keyPoints: [
        "Burning fossil fuels releases CO₂, a greenhouse gas that causes climate change.",
        "Current trend: moving away from fossil fuels towards renewables and low-carbon sources.",
        "Wind and solar are growing fastest as their costs have fallen.",
        "Intermittency must be solved with storage and reliable backup.",
      ],
      thinkDeeper:
        "Replacing fossil fuels is not just about building renewables — it is about keeping supply equal to demand at every instant. That is why storage, grid links and flexible/firm low-carbon power matter as much as the renewables themselves.",
      strategies: ["Separate the cause (CO₂) from the response (renewables)", "Remember intermittency is the key obstacle"],
    },
    {
      heading: "Electricity demand and base load",
      body:
        "Electricity cannot easily be stored in large amounts, so the amount **generated must match the amount used at every instant**. Demand is not constant — it varies through the day and across the year.\n\n- **Base load** is the more-or-less constant minimum demand that is always present (e.g. fridges, street lighting, factories, the night-time minimum). It is best met by stations that run steadily and are cheap to run continuously, such as **nuclear** and large **gas/coal** stations.\n- **Peaks** occur at predictable times — a big morning rise as people wake up, and a large evening peak (cooking, heating, lights, TVs). There are also sudden surges (e.g. everyone switching on kettles in an advert break).\n- To meet peaks, the grid needs stations that can **start up and increase output quickly**: **gas turbines** and **pumped-storage hydroelectric** are ideal because they respond in minutes. Nuclear is poor for this because it cannot change output quickly.\n\nThis is why a real grid uses a **mix** of resources: steady stations for the base load plus fast-responding stations and storage for the peaks.",
      diagrams: [
        {
          caption: "A typical daily demand curve: a low overnight base load with morning and evening peaks.",
          svg:
            '<svg viewBox="0 0 360 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Daily electricity demand curve showing a low overnight base load and morning and evening peaks">\n<line x1="40" y1="150" x2="350" y2="150" stroke="#475569" stroke-width="1.5"/>\n<line x1="40" y1="20" x2="40" y2="150" stroke="#475569" stroke-width="1.5"/>\n<text x="195" y="172" font-size="10" text-anchor="middle" fill="#334155">time of day</text>\n<text x="18" y="90" font-size="10" text-anchor="middle" fill="#334155" transform="rotate(-90 18 90)">demand</text>\n<path d="M40 120 L90 118 L130 70 L170 95 L230 90 L280 40 L320 100 L350 120" fill="none" stroke="#2563eb" stroke-width="2.5"/>\n<line x1="40" y1="128" x2="350" y2="128" stroke="#16a34a" stroke-width="1.5" stroke-dasharray="5 4"/>\n<text x="300" y="142" font-size="9" fill="#16a34a">base load</text>\n<text x="130" y="60" font-size="9" text-anchor="middle" fill="#1e3a8a">morning</text>\n<text x="280" y="32" font-size="9" text-anchor="middle" fill="#1e3a8a">evening peak</text>\n<text x="60" y="115" font-size="9" fill="#64748b">night</text>\n</svg>',
        },
      ],
      keyPoints: [
        "Supply must match demand at every instant — electricity is hard to store.",
        "Base load = constant minimum demand, met by steady stations (nuclear, large gas/coal).",
        "Demand peaks in the morning and (largest) in the evening.",
        "Peaks need fast-responding sources: gas turbines and pumped-storage HEP.",
      ],
      thinkDeeper:
        "Pumped-storage HEP acts like a giant battery: cheap off-peak electricity pumps water uphill, and at peak times that water is released to generate quickly. It is one of the few ways to store electricity on a grid scale.",
      strategies: ["Match steady sources to base load, fast sources to peaks", "Ask: how quickly can this station change its output?"],
    },
    {
      heading: "The National Grid",
      body:
        "The **National Grid** is the network of cables, pylons and transformers that carries electricity from power stations to homes, schools and factories across the country.\n\nThe journey of the electricity:\n\n1. Power stations generate electricity at around 25 kV.\n2. A **step-up transformer** raises the voltage to a very high value (e.g. **400 000 V**) for transmission.\n3. The electricity travels along **high-voltage transmission lines** (the pylons) over long distances.\n4. A **step-down transformer** lowers the voltage in stages for safe use (e.g. **230 V** in UK homes).\n5. The electricity reaches consumers.\n\nTransformers only work with **alternating current (a.c.)**, which is one reason mains electricity is a.c. Transmitting at high voltage is the key to delivering power efficiently over long distances.",
      diagrams: [
        {
          caption: "The National Grid: step-up for transmission, step-down for use.",
          svg:
            '<svg viewBox="0 0 460 130" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="National Grid diagram showing power station, step-up transformer, high voltage lines, step-down transformer and homes">\n<rect x="6" y="50" width="74" height="44" rx="5" fill="#e2e8f0" stroke="#475569"/>\n<text x="43" y="68" font-size="9" text-anchor="middle" fill="#1e293b">Power</text>\n<text x="43" y="80" font-size="9" text-anchor="middle" fill="#1e293b">station 25kV</text>\n<rect x="110" y="50" width="74" height="44" rx="5" fill="#bbf7d0" stroke="#15803d"/>\n<text x="147" y="66" font-size="9" text-anchor="middle" fill="#14532d">Step-UP</text>\n<text x="147" y="80" font-size="9" text-anchor="middle" fill="#14532d">400kV</text>\n<rect x="214" y="50" width="80" height="44" rx="5" fill="#fef9c3" stroke="#a16207"/>\n<text x="254" y="66" font-size="9" text-anchor="middle" fill="#713f12">HV lines</text>\n<text x="254" y="80" font-size="9" text-anchor="middle" fill="#713f12">low current</text>\n<rect x="324" y="50" width="74" height="44" rx="5" fill="#bfdbfe" stroke="#1d4ed8"/>\n<text x="361" y="66" font-size="9" text-anchor="middle" fill="#1e3a8a">Step-DOWN</text>\n<text x="361" y="80" font-size="9" text-anchor="middle" fill="#1e3a8a">230V</text>\n<rect x="424" y="58" width="30" height="28" rx="3" fill="#fbcfe8" stroke="#be185d"/>\n<text x="439" y="76" font-size="9" text-anchor="middle" fill="#831843">Home</text>\n<defs><marker id="g" markerWidth="9" markerHeight="9" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#334155"/></marker></defs>\n<path d="M80 72 H108" stroke="#334155" stroke-width="2" marker-end="url(#g)"/>\n<path d="M184 72 H212" stroke="#334155" stroke-width="2" marker-end="url(#g)"/>\n<path d="M294 72 H322" stroke="#334155" stroke-width="2" marker-end="url(#g)"/>\n<path d="M398 72 H422" stroke="#334155" stroke-width="2" marker-end="url(#g)"/>\n<text x="230" y="30" font-size="9" text-anchor="middle" fill="#64748b">very high voltage = low current = less loss</text>\n</svg>',
        },
      ],
      keyPoints: [
        "Grid = power stations → step-up → HV lines → step-down → consumers.",
        "Step-up transformer raises voltage for transmission.",
        "Step-down transformer lowers voltage for safe use (230 V in homes).",
        "Transformers need a.c., which is why mains is alternating current.",
      ],
      formulae: ["For a transformer (ideal): Vₚ / Vₛ = Nₚ / Nₛ", "P = V × I"],
      strategies: ["Trace the voltage up then back down", "Match each transformer to its job"],
    },
    {
      heading: "Why transmit at high voltage? The I²R argument",
      discovery: {
        problem:
          "Transmission cables have resistance, so some electrical energy is always wasted heating the wires. For a 200 MW station, would it be better to send the power at 10 000 V or at 400 000 V down the same cables? Both deliver the same power — does the voltage really matter?",
        idea: "Yes — hugely. The power lost in the cables depends on the **current**, not the delivered power directly: Pₗₒₛₛ = I²R. For a fixed power, raising the voltage *lowers the current*, and because the loss depends on current **squared**, even a modest cut in current slashes the wasted energy.",
      },
      body:
        "Power is delivered as **P = V × I**. For a fixed amount of power, if you increase the voltage **V**, the current **I** must decrease.\n\nThe energy wasted in the cables (which have resistance **R**) is given by:\n\n**Pₗₒₛₛ = I²R**\n\nBecause the loss depends on **I squared**, reducing the current has a very strong effect:\n\n- Halving the current quarters the power loss.\n- Cutting the current to one-tenth reduces the loss to one-hundredth.\n\nSo the grid uses a **step-up transformer to make V very high and I very low** for transmission, drastically cutting the I²R losses in the long cables. At the consumer end a **step-down transformer** returns the voltage to safe levels.\n\n*Quick example:* deliver 200 MW. At 10 kV the current is I = P/V = 200 000 000 / 10 000 = 20 000 A. At 400 kV the current is only 200 000 000 / 400 000 = 500 A. The current is 40× smaller, so the I²R loss is 40² = **1600 times smaller** in the same cables.",
      keyPoints: [
        "Power loss in cables = I²R (depends on current squared).",
        "For fixed power, P = VI means higher V → lower I.",
        "Lower current → far smaller I²R loss (squared relationship).",
        "Step-up for transmission (high V, low I); step-down for safe use.",
      ],
      whyItWorks:
        "The cables waste energy by heating up, and the heating power is I²R. The transformer cannot change the resistance R of the wires, but it can trade voltage for current at constant power. Pushing the voltage up forces the current down, and squaring a small current makes the loss tiny.",
      formulae: ["P = V × I", "power loss in cables = I²R", "I = P / V"],
      thinkDeeper:
        "Why not also lower R by using thicker cables? You can — but thick copper is heavy and expensive, and lowering R helps only linearly, whereas lowering I helps with the square. Raising the voltage is far cheaper for the same saving.",
      strategies: ["Hold power constant, then trade V for I", "Remember the loss is squared in the current"],
    },
  ],
  learn: {
    bigIdea:
      "We generate electricity by spinning generators, using energy from renewable resources (free but often unreliable) or non-renewable ones (reliable but finite and polluting). The National Grid then delivers that power efficiently by transmitting at very high voltage and low current, because the energy wasted in the cables is I²R.",
    mustKnow: [
      "Renewable = replaced as fast as used (solar, wind, HEP, tidal, wave, geothermal, biomass); non-renewable = finite (coal, oil, gas, nuclear).",
      "A thermal power station: fuel → boiler → steam → turbine → generator → electricity.",
      "Burning fossil fuels releases CO₂; nuclear gives no CO₂ but radioactive waste.",
      "Compare resources on cost, reliability, set-up time, location and environmental impact.",
      "The National Grid: power stations → step-up transformer → HV lines → step-down transformer → consumers.",
      "Electricity is transmitted at high voltage and low current to cut power loss, because loss = I²R.",
      "P = V × I, so for fixed power a higher voltage means a lower current.",
      "Supply must match demand: steady stations (nuclear) cover the base load; fast stations (gas, pumped storage) meet peaks.",
      "The trend is away from fossil fuels (CO₂/climate change) towards renewables, backed by storage for intermittency.",
    ],
    keywords: [
      { term: "Renewable resource", definition: "An energy resource that is replenished as fast as it is used, so it will not run out (e.g. wind, solar)." },
      { term: "Non-renewable resource", definition: "An energy resource that is used up far faster than it forms, so the supply is finite (e.g. coal, nuclear)." },
      { term: "Fossil fuel", definition: "A non-renewable fuel (coal, oil or natural gas) formed from the remains of dead organisms over millions of years." },
      { term: "Nuclear fission", definition: "The splitting of a large nucleus (e.g. uranium) to release energy, used in nuclear power stations." },
      { term: "Turbine", definition: "A wheel of blades spun by steam, wind or water that drives a generator." },
      { term: "Generator", definition: "A device that converts kinetic (rotational) energy into electrical energy." },
      { term: "National Grid", definition: "The network of cables and transformers that distributes electricity from power stations to consumers." },
      { term: "Step-up transformer", definition: "A transformer that increases voltage (and decreases current) for transmission." },
      { term: "Step-down transformer", definition: "A transformer that decreases voltage to a safe level for consumers." },
      { term: "Carbon-neutral", definition: "Releasing no net CO₂ overall; e.g. biomass, because growing plants reabsorb the CO₂ released when burned." },
      { term: "Base load", definition: "The constant minimum electricity demand that is always present, best met by steady stations such as nuclear." },
      { term: "Intermittent", definition: "Producing power only when the weather/conditions allow (e.g. wind, solar), so supply cannot be guaranteed on demand." },
      { term: "Pumped storage", definition: "A hydroelectric scheme that pumps water uphill using cheap off-peak electricity and releases it to generate quickly at peak times." },
    ],
    flashcards: [
      { front: "Why is electricity transmitted at high voltage?", back: "High voltage means low current (P = VI), and the power lost in the cables is I²R, so a low current means far less wasted energy." },
      { front: "List the energy transfers in a thermal power station.", back: "Chemical/nuclear → thermal (boiler/steam) → kinetic (turbine) → electrical (generator)." },
      { front: "Give one advantage and one disadvantage of nuclear power.", back: "Advantage: huge energy output with no CO₂. Disadvantage: dangerous radioactive waste and high set-up cost." },
      { front: "What does a step-up transformer do?", back: "It increases the voltage (and decreases the current) before electricity enters the transmission lines." },
      { front: "Why is biomass called roughly carbon-neutral?", back: "The plants absorb CO₂ as they grow, balancing the CO₂ released when the biomass is burned." },
    ],
  },
  quiz: {
    mcq: [
      {
        id: "ge-mcq-q01",
        question: "Which of these is a renewable energy resource?",
        options: ["Coal", "Natural gas", "Wind", "Uranium"],
        answerIndex: 2,
        explanation: "Wind is replenished continuously by the Sun-driven movement of air, so it never runs out. Coal, gas and uranium are all finite, non-renewable resources.",
        guideRef: "Renewable vs non-renewable resources",
        difficulty: "warmup",
      },
      {
        id: "ge-mcq-q02",
        question: "Which group lists only fossil fuels?",
        options: ["Coal, oil, natural gas", "Coal, uranium, wind", "Oil, solar, gas", "Nuclear, tidal, coal"],
        answerIndex: 0,
        explanation: "The fossil fuels are coal, oil and natural gas — all formed from the remains of dead organisms. Uranium is nuclear, and wind/solar/tidal are renewable.",
        guideRef: "Renewable vs non-renewable resources",
        difficulty: "warmup",
      },
      {
        id: "ge-mcq-q03",
        question: "In a thermal power station, what is the correct order of the main stages?",
        options: [
          "Turbine → boiler → generator → fuel",
          "Fuel → boiler → turbine → generator",
          "Generator → turbine → fuel → boiler",
          "Boiler → generator → fuel → turbine",
        ],
        answerIndex: 1,
        explanation: "Fuel is burned in the boiler to make steam, which spins the turbine, which drives the generator to make electricity.",
        guideRef: "How a thermal power station works",
        difficulty: "core",
        hints: ["What has to happen before steam can be made?", "Something must spin the generator — what?", "Follow the energy from the fuel onwards."],
        strategy: "Follow the energy through each stage",
      },
      {
        id: "ge-mcq-q04",
        question: "What is the job of a generator in a power station?",
        options: [
          "To burn the fuel",
          "To boil the water into steam",
          "To convert kinetic energy into electrical energy",
          "To cool the steam back to water",
        ],
        answerIndex: 2,
        explanation: "A generator converts rotational kinetic energy (from the spinning turbine) into electrical energy.",
        guideRef: "How a thermal power station works",
        difficulty: "core",
        hints: ["What is the very last stage before electricity?", "What kind of energy does the turbine give it?", "Generator: kinetic in, electrical out."],
      },
      {
        id: "ge-mcq-q05",
        question: "Which energy resource produces electricity without releasing carbon dioxide during generation but creates radioactive waste?",
        options: ["Coal", "Nuclear", "Biomass", "Natural gas"],
        answerIndex: 1,
        explanation: "Nuclear power releases no CO₂ while generating but produces long-lived radioactive waste. Coal, gas and biomass all release CO₂ when burned.",
        guideRef: "Non-renewable resources: fossil fuels and nuclear",
        difficulty: "core",
        hints: ["Which resource is not burned at all?", "Which one splits atoms?", "Think about what fission leaves behind."],
      },
      {
        id: "ge-mcq-q06",
        question: "A main disadvantage shared by wind and solar power is that they are…",
        options: ["very expensive to fuel", "unreliable / intermittent", "major sources of CO₂", "quick to run out of fuel"],
        answerIndex: 1,
        explanation: "Wind and solar depend on the weather, so they cannot guarantee power on demand — they are intermittent. They have no fuel cost and produce no CO₂.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["Do they work at night or when it is calm?", "Think about when there is no Sun or no wind.", "The issue is whether power is available on demand."],
      },
      {
        id: "ge-mcq-q07",
        question: "Which renewable resource relies on the heat of hot rocks underground?",
        options: ["Hydroelectric", "Geothermal", "Tidal", "Wave"],
        answerIndex: 1,
        explanation: "Geothermal power uses heat from hot rocks underground to make steam that drives turbines. It works best where hot rocks are near the surface, e.g. Iceland.",
        guideRef: "Renewable resources compared",
        difficulty: "warmup",
      },
      {
        id: "ge-mcq-q08",
        question: "Which resource is usually described as roughly carbon-neutral?",
        options: ["Coal", "Biomass", "Oil", "Nuclear"],
        answerIndex: 1,
        explanation: "Biomass is roughly carbon-neutral because the plants absorb CO₂ as they grow, balancing the CO₂ released when they are burned.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["Which fuel comes from living plants?", "What do growing plants take in from the air?", "Absorbed when growing, released when burned."],
      },
      {
        id: "ge-mcq-q09",
        question: "What does a step-up transformer do in the National Grid?",
        options: [
          "Decreases the voltage for homes",
          "Increases the voltage for transmission",
          "Changes a.c. into d.c.",
          "Increases the resistance of the cables",
        ],
        answerIndex: 1,
        explanation: "A step-up transformer increases the voltage (and decreases the current) before the electricity enters the high-voltage transmission lines.",
        guideRef: "The National Grid",
        difficulty: "core",
        hints: ["'Step-up' refers to which quantity?", "Where in the journey is it used?", "Up before the long cables, down before homes."],
      },
      {
        id: "ge-mcq-q10",
        question: "Electricity is transmitted across the National Grid at very high voltage in order to…",
        options: [
          "increase the current in the cables",
          "reduce the power lost as heat in the cables",
          "make the cables thinner and cheaper",
          "change the frequency of the supply",
        ],
        answerIndex: 1,
        explanation: "High voltage means low current (P = VI). Since power loss = I²R, a low current greatly reduces the energy wasted heating the cables.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "core",
        hints: ["What does high voltage do to the current?", "Which formula gives the loss in the cables?", "Loss depends on current squared."],
        strategy: "Hold power constant, then trade V for I",
      },
      {
        id: "ge-mcq-q11",
        question: "The power wasted in a transmission cable of resistance R carrying current I is given by…",
        options: ["P = V × I", "P = I²R", "P = I / R", "P = V² / I"],
        answerIndex: 1,
        explanation: "The power dissipated (wasted as heat) in the cables is P = I²R, which depends on the current squared.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "core",
        hints: ["Which formula links power, current and resistance?", "It involves the current squared.", "Think heating effect of a current."],
      },
      {
        id: "ge-mcq-q12",
        question: "Transformers are used in the National Grid. This is one reason that mains electricity must be…",
        options: ["direct current (d.c.)", "alternating current (a.c.)", "at constant voltage", "at very low frequency"],
        answerIndex: 1,
        explanation: "Transformers only work with a changing (alternating) current, so the grid uses a.c.",
        guideRef: "The National Grid",
        difficulty: "core",
        hints: ["What kind of current do transformers need?", "Does a transformer work with a steady current?", "a.c. = alternating current."],
      },
      {
        id: "ge-mcq-q13",
        question: "A gas-fired power station is often preferred for meeting sudden peaks in electricity demand because it…",
        options: [
          "produces no CO₂",
          "can be switched on and reach full power quickly",
          "uses a renewable fuel",
          "needs no fuel at all",
        ],
        answerIndex: 1,
        explanation: "Gas stations can start up and reach full output quickly, so they are good for meeting peaks in demand. They still burn fossil fuel and emit CO₂.",
        guideRef: "Non-renewable resources: fossil fuels and nuclear",
        difficulty: "core",
        hints: ["Peaks in demand happen suddenly — what matters?", "Compare start-up speed with nuclear.", "It is about response time, not emissions."],
      },
      {
        id: "ge-mcq-q14",
        question: "Which statement about a thermal power station's efficiency is correct?",
        options: [
          "It is about 100% efficient",
          "Most of the input energy becomes useful electrical energy",
          "Much of the input energy is wasted as heat, so it is typically 30–40% efficient",
          "Efficiency depends only on the voltage used",
        ],
        answerIndex: 2,
        explanation: "Thermal stations waste a lot of energy as heat in the cooling towers and exhaust, so they are usually only 30–40% efficient.",
        guideRef: "How a thermal power station works",
        difficulty: "core",
        hints: ["Where does the wasted energy go?", "Think about the steam in the cooling towers.", "Useful out is much less than total in."],
      },
      {
        id: "ge-mcq-q15",
        question: "Which renewable resource uses the predictable rise and fall of sea level caused by the Moon?",
        options: ["Wave", "Tidal", "Hydroelectric", "Geothermal"],
        answerIndex: 1,
        explanation: "Tidal power uses a barrage to trap water as the tide rises and falls (driven by the Moon's gravity) and releases it through turbines. Tides are very predictable.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["What causes the tides?", "Don't confuse waves (wind-driven) with tides (Moon-driven).", "Tidal flow is highly predictable."],
      },
      {
        id: "ge-mcq-q16",
        question: "A photovoltaic (PV) solar cell transfers energy from…",
        options: [
          "moving water directly into electrical energy",
          "sunlight directly into electrical energy",
          "the wind into kinetic energy",
          "hot rocks into thermal energy",
        ],
        answerIndex: 1,
        explanation: "A photovoltaic cell converts light energy from the Sun directly into electrical energy, without a turbine or generator.",
        guideRef: "Renewable resources compared",
        difficulty: "warmup",
      },
      {
        id: "ge-mcq-q17",
        question: "Which is the correct order of stages in the National Grid, from power station to home?",
        options: [
          "Power station → step-down → HV lines → step-up → home",
          "Power station → step-up → HV lines → step-down → home",
          "Power station → HV lines → step-up → step-down → home",
          "Power station → step-up → step-down → HV lines → home",
        ],
        answerIndex: 1,
        explanation: "Voltage is stepped up for the long-distance high-voltage lines, then stepped down again before reaching homes.",
        guideRef: "The National Grid",
        difficulty: "core",
        hints: ["When do you want the voltage high?", "Up first, then down at the end.", "High voltage is for the long cables."],
      },
      {
        id: "ge-mcq-q18",
        question: "Burning coal contributes to acid rain mainly because it releases…",
        options: ["carbon dioxide", "sulfur dioxide", "oxygen", "water vapour"],
        answerIndex: 1,
        explanation: "Coal (and oil) contain sulfur, so burning them releases sulfur dioxide, which dissolves in rain to form acid rain. CO₂ is a greenhouse gas but is not the main cause of acid rain.",
        guideRef: "Non-renewable resources: fossil fuels and nuclear",
        difficulty: "core",
        hints: ["Which gas makes rain acidic?", "It contains sulfur.", "Not the same as the greenhouse-gas problem."],
      },
      {
        id: "ge-mcq-q19",
        question: "A power station delivers 100 MW. If the transmission voltage is doubled while the power stays the same, the current in the cables will…",
        options: ["double", "halve", "stay the same", "quadruple"],
        answerIndex: 1,
        explanation: "P = VI, so for fixed power, doubling V halves I (I = P/V).",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "core",
        hints: ["Which formula links P, V and I?", "Rearrange to I = P/V.", "If V doubles and P is fixed, what happens to I?"],
        strategy: "Hold power constant, then trade V for I",
      },
      {
        id: "ge-mcq-q20",
        question: "Following on from the previous question, when the current halves the power lost in the cables (P = I²R) becomes…",
        options: ["half", "one quarter", "double", "unchanged"],
        answerIndex: 1,
        explanation: "Loss = I²R. Halving the current gives (½)² = ¼ of the original loss — one quarter.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "challenge",
        hints: ["The loss depends on current squared.", "Halve the current, then square it.", "(½)² = ?"],
        strategy: "Remember the loss is squared in the current",
      },
      {
        id: "ge-mcq-q21",
        question: "A remote farm far from any grid connection, in a sunny region with no river, needs its own electricity supply. The most suitable resource is most likely…",
        options: [
          "a large coal-fired power station",
          "hydroelectric power",
          "solar panels (with battery storage)",
          "a nuclear power station",
        ],
        answerIndex: 2,
        explanation: "With no grid, no river and plenty of sunshine, solar panels (backed by batteries for night-time) are the practical, low-cost choice. Coal and nuclear are impractical at this scale; HEP needs a river.",
        guideRef: "Choosing the right resource for a situation",
        difficulty: "challenge",
        hints: ["What is locally available — sun, water, or coal delivery?", "Which options need a grid connection or a river?", "Match the resource to the location."],
        strategy: "List the factors, then score each option",
      },
      {
        id: "ge-mcq-q22",
        question: "Which statement best explains why raising voltage is preferred to using thicker cables for reducing transmission losses?",
        options: [
          "Thicker cables increase the current",
          "Lowering current cuts loss with the square, while lowering resistance helps only linearly and thick cable is heavy and costly",
          "Voltage has no effect on losses",
          "Thicker cables raise the resistance",
        ],
        answerIndex: 1,
        explanation: "Loss = I²R. Reducing I cuts the loss with the square of the current, whereas reducing R helps only in direct proportion; thick copper is also heavy and expensive, so high voltage is the cheaper route.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "challenge",
        hints: ["Compare how loss depends on I versus on R.", "One relationship is squared, the other linear.", "Also think about the cost and weight of copper."],
        strategy: "Remember the loss is squared in the current",
      },
      {
        id: "ge-mcq-q23",
        question: "Which is a genuine disadvantage of hydroelectric power?",
        options: [
          "It releases large amounts of CO₂ while running",
          "It is unreliable because it depends on the wind",
          "Building the dam floods land and can destroy habitats",
          "The fuel is expensive and runs out",
        ],
        answerIndex: 2,
        explanation: "HEP is reliable and emits no CO₂ while running, but building the dam floods a large area, displacing people and destroying habitats. It needs no fuel.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["Does HEP burn a fuel? Does it depend on wind?", "Think about what happens behind the dam.", "Land upstream is flooded."],
      },
      {
        id: "ge-mcq-q24",
        question: "Compared with renewables, the main advantage of fossil-fuel power stations is that they…",
        options: [
          "never run out of fuel",
          "produce no greenhouse gases",
          "give a reliable supply on demand, day or night and in any weather",
          "have no set-up cost",
        ],
        answerIndex: 2,
        explanation: "Fossil-fuel stations can provide a reliable, controllable supply regardless of weather or time of day. Their drawbacks are CO₂ emissions and finite fuel.",
        guideRef: "Non-renewable resources: fossil fuels and nuclear",
        difficulty: "core",
        hints: ["What can fossil stations do that wind/solar cannot guarantee?", "Think about output at night or in calm weather.", "Reliability is the key strength."],
      },
      {
        id: "ge-mcq-q25",
        question: "Two cables carry the same 50 MW of power. Cable X transmits at 25 kV and cable Y at 250 kV. The ratio of power lost (X : Y) in identical cables is closest to…",
        options: ["1 : 1", "10 : 1", "100 : 1", "1 : 100"],
        answerIndex: 2,
        explanation: "Y's voltage is 10× higher, so its current is 10× lower. Loss = I²R, so X's loss is 10² = 100× that of Y. The ratio is 100 : 1.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "challenge",
        hints: ["Find the ratio of the currents first (I = P/V).", "The voltage ratio is 1 : 10, so the current ratio is 10 : 1.", "Square the current ratio for the loss ratio."],
        strategy: "Remember the loss is squared in the current",
      },
      {
        id: "ge-mcq-q26",
        question: "Which type of power station is best suited to supplying the constant base-load demand?",
        options: [
          "A gas turbine used only at peak times",
          "A nuclear power station running steadily",
          "A single small wind turbine",
          "A pumped-storage hydroelectric scheme",
        ],
        answerIndex: 1,
        explanation: "Base load is the constant minimum demand, best met by a station that runs steadily and is cheap to run continuously, such as a nuclear station. Gas turbines and pumped storage are for fast-responding peaks; a single wind turbine is intermittent.",
        guideRef: "Electricity demand and base load",
        difficulty: "core",
        hints: ["Base load is steady and always present.", "Which station runs continuously and cannot change output quickly?", "Fast-response stations are for peaks, not base load."],
      },
      {
        id: "ge-mcq-q27",
        question: "Which generating method is best able to respond within minutes to a sudden evening peak in demand?",
        options: ["Nuclear", "Pumped-storage hydroelectric", "Coal", "Solar PV"],
        answerIndex: 1,
        explanation: "Pumped-storage HEP can release stored water through its turbines within minutes, making it ideal for sudden peaks. Nuclear and coal change output slowly, and solar gives little output in the evening.",
        guideRef: "Electricity demand and base load",
        difficulty: "challenge",
        hints: ["Which source can start generating almost instantly?", "Think of a method that stores energy ready to release.", "Water released from a high reservoir spins turbines at once."],
      },
      {
        id: "ge-mcq-q28",
        question: "What is the main reason many countries are moving away from fossil fuels towards renewables?",
        options: [
          "Renewables are always cheaper to build",
          "Fossil fuels release CO₂, a greenhouse gas that causes climate change",
          "Renewables are completely reliable",
          "Fossil fuels produce radioactive waste",
        ],
        answerIndex: 1,
        explanation: "The key driver is climate change: burning fossil fuels releases CO₂ and other greenhouse gases that warm the planet. Renewables are not always cheaper to build or fully reliable, and it is nuclear (not fossil fuels) that makes radioactive waste.",
        guideRef: "Climate change and the move towards renewables",
        difficulty: "core",
        hints: ["What gas do fossil fuels release when burned?", "What global problem is that gas linked to?", "It is an environmental driver, not just cost."],
      },
      {
        id: "ge-mcq-q29",
        question: "Wave power generates electricity by…",
        options: [
          "trapping the tide behind a barrage",
          "using the up-and-down movement of surface waves to drive a generator",
          "heating water with hot underground rocks",
          "letting water fall from a high dam",
        ],
        answerIndex: 1,
        explanation: "Wave devices are rocked by the up-and-down motion of surface waves, and this movement drives a generator. Tidal uses a barrage, geothermal uses hot rocks, and HEP uses falling dammed water.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["Don't confuse waves (wind-driven surface motion) with tides.", "What is the device physically doing in the water?", "The bobbing motion drives the generator."],
      },
      {
        id: "ge-mcq-q30",
        question: "A photovoltaic solar panel differs from a coal, wind or hydroelectric station because it…",
        options: [
          "needs no Sun to work",
          "generates electricity directly, without a turbine or generator",
          "produces CO₂ while generating",
          "stores energy as steam",
        ],
        answerIndex: 1,
        explanation: "A PV cell converts sunlight straight into electricity, with no turbine and no generator. Coal, wind and HEP all spin a generator. PV produces no CO₂ and needs sunlight.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["What is missing from a solar PV setup compared to the others?", "Is there any spinning turbine in a PV panel?", "PV converts light energy straight to electrical energy."],
      },
    ],
    qa: [
      {
        id: "ge-qa-q01",
        question: "State what is meant by a renewable energy resource and give two examples. (3 marks)",
        marks: 3,
        modelAnswer:
          "A renewable energy resource is one that is replenished as fast as (or faster than) it is used, so it will not run out. Two examples are wind power and solar power (others: hydroelectric, tidal, wave, geothermal, biomass).",
        markScheme: [
          "Replaced/replenished as fast as it is used | will not run out | not used up",
          "First correct example (wind, solar, HEP, tidal, wave, geothermal, biomass)",
          "Second correct example (different from the first)",
        ],
        commonError: "Giving 'electricity' or 'a battery' as a resource — these are not energy resources. Listing two fossil fuels (which are non-renewable).",
        guideRef: "Renewable vs non-renewable resources",
        difficulty: "warmup",
        hints: ["Focus on how quickly it is replaced.", "Will it ever run out?", "Pick two that nature keeps supplying."],
      },
      {
        id: "ge-qa-q02",
        question: "Describe the energy transfers and the main stages as a coal-fired power station generates electricity. (5 marks)",
        marks: 5,
        modelAnswer:
          "Coal is burned in the boiler, releasing chemical energy as thermal energy. This thermal energy heats water to make high-pressure steam. The steam rushes past the blades of a turbine, making it spin, so thermal energy is transferred to kinetic energy. The spinning turbine drives a generator, which transfers the kinetic energy into electrical energy. The energy chain is chemical → thermal → kinetic → electrical.",
        markScheme: [
          "Coal is burned in the boiler | chemical energy released",
          "Thermal energy heats water to make steam",
          "Steam spins the turbine | thermal to kinetic",
          "Turbine drives the generator | kinetic to electrical",
          "Correct overall transfer: chemical to thermal to kinetic to electrical",
        ],
        commonError: "Saying the generator 'makes' the steam or that burning the coal directly produces electricity — the steam and turbine come in between.",
        guideRef: "How a thermal power station works",
        difficulty: "core",
        hints: ["Start with the fuel and the boiler.", "What does the steam do to the turbine?", "Name the energy type at every stage."],
      },
      {
        id: "ge-qa-q03",
        question: "Compare nuclear power with coal power, giving one advantage and one disadvantage of using nuclear instead of coal. (4 marks)",
        marks: 4,
        modelAnswer:
          "Advantage: nuclear power releases no carbon dioxide during generation, whereas burning coal releases CO₂ (a greenhouse gas) and other pollutants such as sulfur dioxide; nuclear also gives a very high energy output from a small mass of fuel. Disadvantage: nuclear power produces dangerous radioactive waste that must be stored safely for thousands of years, and the set-up and decommissioning costs are very high; coal stations are cheaper and quicker to build.",
        markScheme: [
          "Advantage: nuclear emits no CO₂ / no greenhouse gas during generation | very high output per unit fuel",
          "Linked comparison to coal (coal emits CO₂ / pollutants)",
          "Disadvantage: nuclear produces radioactive waste | high set-up/decommissioning cost | accident risk",
          "Linked comparison to coal (coal cheaper / quicker to build)",
        ],
        commonError: "Stating advantages without comparing them to coal, or claiming nuclear 'produces no waste'. It produces radioactive waste, just not CO₂.",
        guideRef: "Non-renewable resources: fossil fuels and nuclear",
        difficulty: "core",
        hints: ["Think about emissions for one point.", "Think about waste or cost for the other.", "Always link your point back to coal."],
      },
      {
        id: "ge-qa-q04",
        question: "Explain why both wind and solar power are described as unreliable, and suggest one way an electricity network can cope with this. (4 marks)",
        marks: 4,
        modelAnswer:
          "Wind power only generates electricity when the wind is blowing, and solar power only generates during daylight and is reduced by cloud, so neither can guarantee a supply on demand — their output varies with the weather and time of day. A network can cope by storing surplus energy (for example in batteries or by pumped-storage hydroelectric) to release when output is low, or by keeping other reliable stations (such as gas) ready to make up the shortfall.",
        markScheme: [
          "Wind only works when it is windy | output varies with wind",
          "Solar only works in daylight / reduced by cloud | output varies",
          "So supply cannot be guaranteed on demand | intermittent",
          "Sensible coping method: energy storage (batteries/pumped storage) OR backup reliable stations",
        ],
        commonError: "Saying they are unreliable because 'they run out of fuel' — they have no fuel; the issue is the weather.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["When does a wind turbine produce nothing?", "When does a solar panel produce nothing?", "How could you save energy for later, or what backup could help?"],
      },
      {
        id: "ge-qa-q05",
        question: "Describe the role of the step-up and step-down transformers in the National Grid. (4 marks)",
        marks: 4,
        modelAnswer:
          "At the power station, a step-up transformer increases the voltage to a very high value (e.g. 400 000 V) for transmission. This high voltage means a low current, which reduces the power lost as heat in the transmission cables. Near the consumers, a step-down transformer decreases the voltage back to a much lower, safe value (e.g. 230 V) so that it can be used safely in homes and businesses.",
        markScheme: [
          "Step-up transformer increases the voltage (for transmission)",
          "High voltage means low current | reduces power loss in cables",
          "Step-down transformer decreases the voltage near consumers",
          "Lower voltage is safe for use in homes (e.g. 230 V)",
        ],
        commonError: "Mixing up the two transformers, or saying the step-up transformer increases the current — it decreases it.",
        guideRef: "The National Grid",
        difficulty: "core",
        hints: ["Where is each transformer in the journey?", "What does 'step-up' do to the voltage?", "Why is a low voltage wanted at the end?"],
      },
      {
        id: "ge-qa-q06",
        question: "Electricity is transmitted across the National Grid at very high voltage. Explain, using the equation for power loss, why this reduces wasted energy. (5 marks)",
        marks: 5,
        modelAnswer:
          "The power transmitted is given by P = V × I, so for a fixed amount of power, increasing the voltage V decreases the current I. The power wasted as heat in the transmission cables is given by P_loss = I²R, where R is the cable resistance. Because the loss depends on the current squared, reducing the current has a very large effect: for example, cutting the current to one-tenth reduces the loss to one-hundredth. Therefore transmitting at a very high voltage keeps the current low and greatly reduces the energy wasted heating the cables, even though the same power is delivered.",
        markScheme: [
          "P = V × I, so for fixed power higher V means lower I",
          "Power loss in cables = I²R",
          "Loss depends on current squared",
          "So a small reduction in current gives a large reduction in loss",
          "Therefore high voltage (low current) wastes much less energy",
        ],
        commonError: "Saying high voltage reduces loss because 'loss = V²R' or because 'high voltage carries more power'. The loss depends on I²R, and it is the lower current that helps.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "challenge",
        hints: ["Start from P = VI to link voltage and current.", "Which equation gives the loss in the cables?", "Stress that the loss depends on the current squared."],
        strategy: "Hold power constant, then trade V for I",
        solutions: [
          {
            label: "Method: link the two equations",
            steps: [
              "Delivered power is fixed: P = V × I, so I = P / V.",
              "Increasing V therefore decreases I (inverse relationship).",
              "Energy is wasted heating the cables: P_loss = I²R.",
              "Substitute the smaller I: because it is squared, the loss falls steeply.",
              "Conclusion: high V → low I → much smaller I²R loss for the same delivered power.",
            ],
          },
        ],
      },
      {
        id: "ge-qa-q07",
        question: "A power station supplies 240 MW of power. The transmission cables have a total resistance of 5 Ω. Calculate the current in the cables and the power lost (a) when the transmission voltage is 24 000 V, and (b) when it is 400 000 V. Comment on the comparison. (6 marks)",
        marks: 6,
        modelAnswer:
          "(a) At 24 000 V: I = P / V = 240 000 000 / 24 000 = 10 000 A. Power loss = I²R = (10 000)² × 5 = 1.0 × 10⁸ × 5 = 5.0 × 10⁸ W = 500 MW (more than the power supplied, so transmitting at this low voltage is impossible in practice). (b) At 400 000 V: I = 240 000 000 / 400 000 = 600 A. Power loss = (600)² × 5 = 360 000 × 5 = 1.8 × 10⁶ W = 1.8 MW. The higher voltage gives a far smaller current, and because loss = I²R the wasted power drops dramatically (from 500 MW to about 1.8 MW), which is why the grid transmits at very high voltage.",
        markScheme: [
          "(a) I = P/V = 10 000 A",
          "(a) Power loss = I²R = 5.0 × 10⁸ W (500 MW)",
          "(b) I = P/V = 600 A",
          "(b) Power loss = I²R = 1.8 × 10⁶ W (1.8 MW)",
          "Correct use of P = VI then P = I²R",
          "Comment: high voltage gives low current gives far less loss (loss proportional to I²)",
        ],
        commonError: "Forgetting to convert MW to W (240 MW = 2.4 × 10⁸ W), or using P = I²R with the delivered power instead of computing the current first.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "challenge",
        hints: ["Convert 240 MW into watts first.", "Use I = P/V to get the current at each voltage.", "Then use P_loss = I²R for each case and compare."],
        strategy: "Hold power constant, then trade V for I",
        solutions: [
          {
            label: "Method 1: current first, then I²R",
            steps: [
              "Convert power: 240 MW = 2.4 × 10⁸ W.",
              "At 24 kV: I = P/V = 2.4 × 10⁸ / 24 000 = 10 000 A.",
              "Loss = I²R = (10 000)² × 5 = 5.0 × 10⁸ W = 500 MW.",
              "At 400 kV: I = 2.4 × 10⁸ / 400 000 = 600 A.",
              "Loss = (600)² × 5 = 1.8 × 10⁶ W = 1.8 MW.",
            ],
          },
          {
            label: "Method 2: using the ratio shortcut",
            steps: [
              "Voltage rises by factor 400 000 / 24 000 ≈ 16.7×.",
              "For fixed power, current falls by the same factor (÷16.7).",
              "Loss is proportional to I², so loss falls by 16.7² ≈ 278×.",
              "500 MW ÷ 278 ≈ 1.8 MW, matching the direct calculation.",
            ],
          },
        ],
      },
      {
        id: "ge-qa-q08",
        question: "A wind turbine transfers 18 MJ of energy to electricity in 1 minute. Calculate its useful power output. (3 marks)",
        marks: 3,
        modelAnswer:
          "Power P = E / t. The time must be in seconds: 1 minute = 60 s. P = 18 000 000 J / 60 s = 300 000 W = 300 kW.",
        markScheme: [
          "Use P = E / t",
          "Convert time to seconds (1 min = 60 s) and/or energy to joules (18 MJ = 1.8 × 10⁷ J)",
          "P = 300 000 W = 300 kW (with unit)",
        ],
        commonError: "Dividing by 1 instead of 60 (forgetting to convert minutes to seconds), giving an answer 60× too large.",
        guideRef: "How a thermal power station works",
        difficulty: "core",
        hints: ["Which equation links energy, power and time?", "Convert the minute into seconds.", "P = E / t with E in joules and t in seconds."],
        solutions: [
          {
            label: "Method: P = E/t with consistent units",
            steps: [
              "E = 18 MJ = 18 000 000 J.",
              "t = 1 minute = 60 s.",
              "P = E/t = 18 000 000 / 60 = 300 000 W.",
              "Express as 300 kW.",
            ],
          },
        ],
      },
      {
        id: "ge-qa-q09",
        question: "A coal-fired power station takes in 800 MJ of energy from its fuel each second and delivers 320 MW of electrical power. Calculate its efficiency and state two reasons why it is not 100% efficient. (4 marks)",
        marks: 4,
        modelAnswer:
          "Each second the input energy is 800 MJ, so the input power is 800 MW, and the useful output power is 320 MW. Efficiency = (useful output ÷ total input) × 100% = (320 / 800) × 100% = 40%. It is not 100% efficient because much of the energy is wasted as thermal energy: heat carried away in the steam/cooling towers and lost in the exhaust gases, and some energy is lost to friction and sound in the turbine and generator.",
        markScheme: [
          "Recognise input power = 800 MW (800 MJ per second)",
          "Efficiency = useful ÷ total × 100% = 320/800 × 100%",
          "= 40%",
          "Two valid loss reasons (e.g. heat in cooling towers/steam, exhaust gases, friction/sound)",
        ],
        commonError: "Dividing the wrong way (800/320). Both input and output are already 'per second', so the ratio of powers gives the efficiency directly.",
        guideRef: "How a thermal power station works",
        difficulty: "core",
        hints: ["800 MJ per second is the same as 800 MW.", "Efficiency = useful ÷ total × 100%.", "Where does the wasted energy go in a thermal station?"],
        solutions: [
          {
            label: "Method: efficiency ratio",
            steps: [
              "Input power = 800 MJ/s = 800 MW.",
              "Useful output power = 320 MW.",
              "Efficiency = (320 / 800) × 100% = 40%.",
              "Losses: thermal energy in cooling towers/steam and exhaust; friction and sound in turbine/generator.",
            ],
          },
        ],
      },
      {
        id: "ge-qa-q10",
        question: "A small, remote island has strong, steady winds all year, no fossil-fuel supply, no rivers, and no connection to a mainland grid. Evaluate which energy resource would be most suitable for generating its electricity, justifying your choice. (6 marks)",
        marks: 6,
        modelAnswer:
          "Wind power is the most suitable choice. The island has strong, steady winds all year, so wind turbines would generate reliably for most of the time, and there is no fuel to buy or deliver. Fossil-fuel and nuclear stations are unsuitable: there is no fossil-fuel supply or grid connection to import fuel, and a nuclear station would be far too large, expensive and slow to build for a small island. Hydroelectric is ruled out because there are no rivers. The main drawback of wind is that it produces nothing when the wind drops, so it should be paired with energy storage (such as batteries) or a small backup, and possibly solar, to guarantee supply at all times. Overall, wind power best matches the island's available resource, its lack of a grid, and the need for low running costs.",
        markScheme: [
          "Chooses wind power (a defensible renewable) with clear justification",
          "Uses the island's resource: strong steady wind all year",
          "Rejects fossil/nuclear: no fuel supply / no grid / too large or costly",
          "Rejects hydroelectric: no rivers",
          "Identifies wind's weakness: intermittent / nothing when wind drops",
          "Suggests storage or backup (batteries / solar) to ensure reliable supply",
        ],
        commonError: "Choosing a resource without using the specific clues in the question (e.g. picking HEP despite 'no rivers'), or giving advantages with no evaluation of drawbacks.",
        guideRef: "Choosing the right resource for a situation",
        difficulty: "challenge",
        hints: ["List what the island actually has and lacks.", "Cross out resources that need a grid, fuel, or a river.", "Pick the best match, then deal with its main weakness."],
        strategy: "List the factors, then score each option",
      },
      {
        id: "ge-qa-q11",
        question: "Explain why fossil fuels are described as non-renewable and outline two environmental problems caused by burning them. (4 marks)",
        marks: 4,
        modelAnswer:
          "Fossil fuels are non-renewable because they formed from the remains of dead organisms over millions of years and are being used up far faster than they can be replaced, so the supply is finite and will eventually run out. Burning them releases carbon dioxide, a greenhouse gas that contributes to global warming and climate change. Burning coal and oil also releases sulfur dioxide, which dissolves in rain to cause acid rain that damages plants, buildings and waterways.",
        markScheme: [
          "Formed over millions of years | finite supply",
          "Used up far faster than replaced | will run out (non-renewable)",
          "First problem: CO₂ / greenhouse gas to global warming/climate change",
          "Second problem: sulfur dioxide to acid rain (or other valid pollutant problem)",
        ],
        commonError: "Saying fossil fuels are renewable because 'more can form' — they form far too slowly to replace what we use.",
        guideRef: "Non-renewable resources: fossil fuels and nuclear",
        difficulty: "core",
        hints: ["How long do fossil fuels take to form, versus how fast we use them?", "Name the greenhouse gas released.", "What gas from coal/oil causes acid rain?"],
      },
      {
        id: "ge-qa-q12",
        question: "A student claims: 'Using thicker copper cables is always the best way to reduce energy losses in transmission, so we don't really need high voltage.' Discuss whether this claim is correct, referring to the relevant physics. (5 marks)",
        marks: 5,
        modelAnswer:
          "The claim is not correct. The power lost in the cables is P_loss = I²R. Thicker cables do reduce losses because a larger cross-sectional area gives a lower resistance R, and the loss is proportional to R. However, this only helps in direct (linear) proportion, and thick copper cables are very heavy and expensive, which is impractical over long distances. Transmitting at high voltage tackles the current instead: from P = VI, a higher voltage gives a lower current, and because the loss depends on the current squared (I²R), even a moderate cut in current produces a much larger fall in losses than a similar cut in resistance. So high voltage is a far more effective and cheaper way to reduce losses, and is used together with reasonably sized cables — not replaced by thick cables alone.",
        markScheme: [
          "States the claim is wrong / incomplete",
          "P_loss = I²R; thicker cable lowers R so does reduce loss (linearly)",
          "But thick copper is heavy/expensive/impractical over long distance",
          "High voltage lowers current via P = VI",
          "Loss proportional to I², so cutting current is far more effective than cutting R — high voltage is better/cheaper",
        ],
        commonError: "Treating R and I as having the same effect on the loss. The loss is linear in R but depends on the square of I, so reducing current is much more powerful.",
        guideRef: "Why transmit at high voltage? The I²R argument",
        difficulty: "challenge",
        hints: ["Write down P_loss = I²R and see what each factor does.", "Does thicker cable change R or I?", "Compare a linear effect (R) with a squared effect (I)."],
        strategy: "Remember the loss is squared in the current",
      },
      {
        id: "ge-qa-q13",
        question: "Explain what is meant by the 'base load' of electricity demand, and describe why a national grid uses a mix of different power stations to meet demand through the day. (5 marks)",
        marks: 5,
        modelAnswer:
          "The base load is the more-or-less constant minimum demand for electricity that is always present, day and night (for example fridges, street lighting and factories). Demand is not constant, though: it rises to peaks at predictable times, with a morning rise and a large evening peak, plus sudden short surges. Because electricity cannot easily be stored in large amounts, the amount generated must match demand at every instant. The grid therefore uses a mix: steady stations that are cheap to run continuously (such as nuclear and large gas or coal stations) supply the base load, while stations that can change output quickly (such as gas turbines and pumped-storage hydroelectric) are switched on to meet the peaks. Using a mix means demand can always be matched without wasting fuel running expensive fast-response stations all the time.",
        markScheme: [
          "Base load = constant/minimum demand that is always present",
          "Demand varies through the day | peaks (e.g. morning/evening)",
          "Supply must match demand at every instant (electricity hard to store)",
          "Steady stations (nuclear/large gas/coal) supply the base load",
          "Fast-responding stations (gas turbine/pumped storage) meet the peaks",
        ],
        commonError: "Describing base load as the maximum demand, or saying one type of station can do everything — fast-response and steady stations have different roles.",
        guideRef: "Electricity demand and base load",
        difficulty: "challenge",
        hints: ["Base load is the steady minimum, not the maximum.", "When does demand peak during a day?", "Match steady stations to base load and fast ones to peaks."],
      },
      {
        id: "ge-qa-q14",
        question: "Biomass is often described as a roughly carbon-neutral renewable resource. Explain what this means and give one advantage and one disadvantage of using biomass to generate electricity. (4 marks)",
        marks: 4,
        modelAnswer:
          "Carbon-neutral means there is little or no net release of CO₂ overall: although burning biomass releases CO₂, the plants absorbed an approximately equal amount of CO₂ from the air as they grew, so the net addition to the atmosphere is small. It is renewable because new crops can be grown to replace what is burned. An advantage is that it makes use of plant or waste material and adds little net CO₂, and it is reliable like a fossil-fuel station (it can be burned on demand). A disadvantage is that burning still releases CO₂ and other pollutants at the point of use, and growing the crops needs large areas of land that could otherwise be used to grow food.",
        markScheme: [
          "Carbon-neutral = little/no net CO₂ overall",
          "Because growing plants absorb CO₂ that balances the CO₂ released when burned",
          "Advantage: uses waste/plants | low net CO₂ | reliable (burn on demand) | renewable",
          "Disadvantage: still emits CO₂/pollutants when burned | large land use / competes with food",
        ],
        commonError: "Saying biomass releases no CO₂ at all — it does release CO₂ when burned; the point is that growth reabsorbs a similar amount, so the net is roughly zero.",
        guideRef: "Renewable resources compared",
        difficulty: "core",
        hints: ["What does 'net' CO₂ mean here?", "Where does the balancing CO₂ get absorbed?", "Give one plus and one minus, including land use."],
      },
    ],
  },
};
