import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const rp: Topic = {
  id: "rp",
  code: "RP",
  number: 7,
  title: "Radioactivity and Particles",
  subject: "Physics",
  icon: "☢️",
  color: "#a855f7",
  intro: "Inside the atom. Radioactive decay, half-life, nuclear fission and fusion, and how radiation is used and made safe.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "Inside the atom. Radioactive decay, half-life, nuclear fission and fusion, and how radiation is used and made safe.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Radioactivity and Particles", definition: "Inside the atom. Radioactive decay, half-life, nuclear fission and fusion, and how radiation is used and made safe." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "rp-mcq-q01",
        question: "Placeholder question for Radioactivity and Particles — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "rp-qa-q01",
        question: "Placeholder exam question for Radioactivity and Particles. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
