import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const slg: Topic = {
  id: "slg",
  code: "SLG",
  number: 8,
  title: "Solids, Liquids and Gases",
  subject: "Physics",
  icon: "💧",
  color: "#3b82f6",
  intro: "The particle model in action: density, pressure, changes of state and the gas laws.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "The particle model in action: density, pressure, changes of state and the gas laws.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Solids, Liquids and Gases", definition: "The particle model in action: density, pressure, changes of state and the gas laws." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "slg-mcq-q01",
        question: "Placeholder question for Solids, Liquids and Gases — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "slg-qa-q01",
        question: "Placeholder exam question for Solids, Liquids and Gases. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
