import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const wep: Topic = {
  id: "wep",
  code: "WEP",
  number: 5,
  title: "Work, Energy and Power",
  subject: "Physics",
  icon: "🔋",
  color: "#10b981",
  intro: "Energy is never made or destroyed — only moved and stored. Work done, kinetic and gravitational energy, efficiency and power.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "Energy is never made or destroyed — only moved and stored. Work done, kinetic and gravitational energy, efficiency and power.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Work, Energy and Power", definition: "Energy is never made or destroyed — only moved and stored. Work done, kinetic and gravitational energy, efficiency and power." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "wep-mcq-q01",
        question: "Placeholder question for Work, Energy and Power — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "wep-qa-q01",
        question: "Placeholder exam question for Work, Energy and Power. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
