import type { Topic } from "../types";

// Waves — Edexcel International GCSE Physics (4PH1). Mirrors the AoPS house style
// of the Heat Transfer template (discovery openers, whyItWorks, strategies,
// tiered difficulty, hint ladders, multi-method solutions) with a deeper question pool.

export const wv: Topic = {
  id: "wv",
  code: "WV",
  number: 2,
  title: "Waves",
  subject: "Physics",
  icon: "🌊",
  color: "#06b6d4",
  intro:
    "A wave carries energy from one place to another without carrying matter with it. In this topic you'll learn to describe waves (amplitude, wavelength, frequency, period), use the wave equation v = f λ, explain reflection, refraction and total internal reflection, work with the electromagnetic spectrum, understand sound, and draw ray diagrams for lenses.",
  guide: [
    {
      heading: "What is a wave? Transverse vs longitudinal",
      discovery: {
        problem:
          "Drop a cork onto a pond and flick the surface. Ripples race outward and the cork bobs up and down — but it never travels across to the far bank. Something clearly moves outward fast, yet the water stays put. What is actually travelling?",
        idea: "What travels is energy (and the pattern of the disturbance), not the water itself. Each bit of water just oscillates about a fixed point and passes the energy on to its neighbour. Every wave is energy transfer without net transfer of matter.",
      },
      body:
        "A **wave** is an oscillation (vibration) that transfers **energy** from place to place **without transferring matter**. The particles of the medium just vibrate about a fixed position.\n\nThere are two kinds of wave, classified by the *direction of vibration* compared with the *direction the wave travels*:\n\n1. **Transverse wave** — the vibrations are at **right angles (90°)** to the direction of energy transfer. Examples: water waves, all electromagnetic waves (light, radio…), a wave on a rope.\n2. **Longitudinal wave** — the vibrations are **parallel** to (along) the direction of energy transfer. The medium forms **compressions** (squashed together) and **rarefactions** (spread apart). Examples: sound waves, a push-pull wave on a slinky.\n\n*Mechanical* waves (water, sound, slinky) need a **medium** to travel through. *Electromagnetic* waves do not — they can travel through a vacuum.",
      diagrams: [
        {
          caption: "A transverse wave with amplitude and wavelength labelled, plus crest and trough.",
          svg:
            '<svg viewBox="0 0 360 160" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A transverse wave showing crest, trough, amplitude measured from the middle line, and wavelength between two crests">\n<line x1="20" y1="80" x2="340" y2="80" stroke="#94a3b8" stroke-dasharray="4 4"/>\n<text x="345" y="84" font-size="9" fill="#64748b">rest</text>\n<path d="M20 80 C50 20 90 20 120 80 C150 140 190 140 220 80 C250 20 290 20 320 80" fill="none" stroke="#0e7490" stroke-width="3"/>\n<line x1="70" y1="80" x2="70" y2="38" stroke="#dc2626" stroke-width="1.5" marker-end="url(#au)" marker-start="url(#ad)"/>\n<text x="76" y="62" font-size="10" fill="#b91c1c">amplitude</text>\n<line x1="70" y1="32" x2="270" y2="32" stroke="#1d4ed8" stroke-width="1.5" marker-end="url(#ar)" marker-start="url(#al)"/>\n<text x="150" y="26" font-size="10" fill="#1d4ed8">wavelength (one full wave)</text>\n<text x="70" y="20" font-size="9" text-anchor="middle" fill="#334155">crest</text>\n<text x="170" y="155" font-size="9" text-anchor="middle" fill="#334155">trough</text>\n<defs>\n<marker id="au" markerWidth="8" markerHeight="8" refX="4" refY="1" orient="auto"><path d="M0 6 L4 0 L8 6 z" fill="#dc2626"/></marker>\n<marker id="ad" markerWidth="8" markerHeight="8" refX="4" refY="6" orient="auto"><path d="M0 0 L4 6 L8 0 z" fill="#dc2626"/></marker>\n<marker id="ar" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#1d4ed8"/></marker>\n<marker id="al" markerWidth="8" markerHeight="8" refX="0" refY="3" orient="auto"><path d="M6 0 L0 3 L6 6 z" fill="#1d4ed8"/></marker>\n</defs>\n</svg>',
        },
        {
          caption: "A longitudinal wave: compressions (close lines) and rarefactions (spread lines).",
          svg:
            '<svg viewBox="0 0 360 80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A longitudinal wave shown as vertical lines bunched into compressions and spread out into rarefactions, with the wave travelling left to right">\n<g stroke="#0e7490" stroke-width="2">\n<line x1="20" y1="20" x2="20" y2="60"/><line x1="26" y1="20" x2="26" y2="60"/><line x1="31" y1="20" x2="31" y2="60"/>\n<line x1="55" y1="20" x2="55" y2="60"/><line x1="75" y1="20" x2="75" y2="60"/>\n<line x1="105" y1="20" x2="105" y2="60"/><line x1="111" y1="20" x2="111" y2="60"/><line x1="116" y1="20" x2="116" y2="60"/>\n<line x1="140" y1="20" x2="140" y2="60"/><line x1="160" y1="20" x2="160" y2="60"/>\n<line x1="190" y1="20" x2="190" y2="60"/><line x1="196" y1="20" x2="196" y2="60"/><line x1="201" y1="20" x2="201" y2="60"/>\n<line x1="225" y1="20" x2="225" y2="60"/><line x1="245" y1="20" x2="245" y2="60"/>\n<line x1="275" y1="20" x2="275" y2="60"/><line x1="281" y1="20" x2="281" y2="60"/><line x1="286" y1="20" x2="286" y2="60"/>\n</g>\n<text x="28" y="74" font-size="9" text-anchor="middle" fill="#b91c1c">compression</text>\n<text x="130" y="74" font-size="9" text-anchor="middle" fill="#1d4ed8">rarefaction</text>\n<line x1="300" y1="40" x2="345" y2="40" stroke="#1e293b" stroke-width="2" marker-end="url(#dir)"/>\n<defs><marker id="dir" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#1e293b"/></marker></defs>\n</svg>',
        },
      ],
      keyPoints: [
        "A wave transfers energy without transferring matter.",
        "Transverse: vibrations perpendicular (90°) to wave travel.",
        "Longitudinal: vibrations parallel to wave travel; has compressions and rarefactions.",
        "Mechanical waves need a medium; EM waves can travel through a vacuum.",
      ],
      whyItWorks:
        "Each particle is connected to its neighbours. When one is disturbed it pulls/pushes the next, passing the energy along, then returns to its rest position — so the disturbance moves on but the particles stay roughly where they started.",
      strategies: ["Classify by comparing vibration direction with travel direction", "Find a familiar example for each type"],
    },
    {
      heading: "Describing waves: amplitude, wavelength, frequency, period",
      body:
        "Four quantities describe any wave:\n\n- **Amplitude (A)** — the maximum displacement of a particle from its rest position (metres, m). Bigger amplitude = more energy.\n- **Wavelength (λ, lambda)** — the distance for one complete wave, e.g. crest to crest (metres, m).\n- **Frequency (f)** — the number of complete waves passing a point each second. Unit: **hertz (Hz)**. 1 Hz = 1 wave per second.\n- **Period (T)** — the time for one complete wave to pass a point (seconds, s).\n\nFrequency and period are reciprocals — they describe the same thing from opposite directions:\n\n`f = 1 / T`   and   `T = 1 / f`\n\nFor example, if 5 waves pass each second then f = 5 Hz, and each one takes T = 1/5 = 0.2 s.",
      formulae: ["f = 1 / T", "T = 1 / f", "frequency in Hz, period in s"],
      keyPoints: [
        "Amplitude = maximum displacement from rest (linked to energy).",
        "Wavelength λ = length of one full wave (m).",
        "Frequency f = waves per second (Hz); Period T = time for one wave (s).",
        "f and T are reciprocals: f = 1/T.",
      ],
      whyItWorks:
        "If one wave takes T seconds to pass, then in one second 1/T waves pass — that count per second is exactly the frequency. So f and T must be reciprocals.",
      strategies: ["Write the unit next to each symbol before calculating", "Check f and T are reciprocals as a sanity test"],
    },
    {
      heading: "The wave equation v = f λ",
      discovery: {
        problem:
          "Waves on the sea arrive at the shore one every 2 seconds, and each wave is 8 m long, crest to crest. Can you work out how fast the waves are moving — without timing a single crest across a measured distance?",
        idea: "In the time for one wave to pass (the period), the wave moves forward by exactly one wavelength. Speed = distance ÷ time = λ ÷ T = λ × f. Here f = 1/2 = 0.5 Hz, so v = 0.5 × 8 = 4 m/s.",
      },
      body:
        "The **wave speed** is linked to frequency and wavelength by the **wave equation**:\n\n`v = f λ`\n\nwhere **v** is wave speed in metres per second (m/s), **f** is frequency in hertz (Hz), and **λ** is wavelength in metres (m).\n\nRearrange it depending on what you need:\n\n- `f = v / λ`\n- `λ = v / f`\n\n**Worked example.** A sound wave has frequency 170 Hz and wavelength 2.0 m. Speed = f λ = 170 × 2.0 = **340 m/s**.\n\n**Key idea for a single medium:** the speed of a wave is fixed by the medium it travels in. So if you *increase the frequency*, the *wavelength must decrease* to keep v = f λ the same (f and λ are inversely proportional).",
      formulae: ["v = f λ", "f = v / λ", "λ = v / f", "(combine with f = 1/T if given period)"],
      strategies: [
        "Write down v = f λ, list what you know with units, then rearrange",
        "If given period T, first convert to frequency with f = 1/T",
        "Sanity-check: in one medium, higher f means shorter λ",
      ],
      whyItWorks:
        "During one period T a single wave advances exactly one wavelength λ. So v = distance/time = λ/T. Since 1/T = f, this is v = f λ.",
      keyPoints: [
        "v = f λ (speed = frequency × wavelength).",
        "Rearrange to f = v/λ or λ = v/f.",
        "Convert period to frequency first: f = 1/T.",
        "In one medium v is fixed, so f and λ are inversely proportional.",
      ],
    },
    {
      heading: "Wavefronts, the ripple tank, reflection and the law of reflection",
      discovery: {
        problem:
          "How do scientists study how waves behave — reflect, refract, spread out — when light waves are far too small and fast to watch? They needed a way to make waves big, slow and visible.",
        idea: "Use a **ripple tank**: a shallow tray of water with a vibrating bar (a dipper) making straight wavefronts, or a point making circular ones. A lamp above casts the bright crests and dark troughs as shadows on the floor, so you can see, measure and photograph wave behaviour directly.",
      },
      body:
        "A **wavefront** is a line joining points on a wave that are all in step (all at a crest, say). Wavefronts are perpendicular to the direction the wave travels; the arrow showing direction is a **ray**. The distance between two neighbouring wavefronts is one **wavelength**.\n\n**The ripple tank** is the standard way to study waves in the lab. A motor vibrates a straight bar that dips into shallow water, sending out straight wavefronts; a small ball makes circular ones. A lamp above the tank projects the crests and troughs as bright and dark bands onto a screen below. With it you can show:\n\n- **Reflection** off a straight barrier (wavefronts bounce off, angle in = angle out).\n- **Refraction** — placing a sheet of glass under the water makes it shallower there, so the waves slow down, the wavelength shortens and the wavefronts change direction.\n- The link between the bar's frequency and the wavelength (faster vibration → wavefronts closer together).\n\nWhen a wave hits a barrier it can be **reflected**. We measure angles from the **normal** — an imaginary line drawn at 90° to the surface at the point where the ray hits.\n\n**The law of reflection:**\n\n`angle of incidence (i) = angle of reflection (r)`\n\nBoth angles are measured between the ray and the normal (never from the surface itself). In reflection the wave **speed, frequency and wavelength stay the same** (it is in the same medium) — only the direction changes. Reflection is how mirrors work and how we see most objects.",
      diagrams: [
        {
          caption: "Ripple tank: a vibrating bar makes straight wavefronts; a lamp projects crests and troughs onto a screen below.",
          svg:
            '<svg viewBox="0 0 320 150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A ripple tank with a lamp above, a vibrating bar making straight wavefronts in shallow water, and bright and dark bands projected onto a screen below">\n<circle cx="160" cy="16" r="9" fill="#fde047" stroke="#ca8a04"/>\n<text x="173" y="19" font-size="8" fill="#334155">lamp</text>\n<line x1="160" y1="25" x2="130" y2="55" stroke="#fcd34d"/><line x1="160" y1="25" x2="190" y2="55" stroke="#fcd34d"/>\n<rect x="40" y="55" width="240" height="34" fill="#bae6fd" stroke="#0369a1"/>\n<rect x="50" y="48" width="6" height="14" fill="#475569"/><text x="36" y="46" font-size="8" fill="#334155">bar</text>\n<g stroke="#0e7490" stroke-width="2" fill="none"><line x1="70" y1="57" x2="70" y2="87"/><line x1="92" y1="57" x2="92" y2="87"/><line x1="114" y1="57" x2="114" y2="87"/><line x1="136" y1="57" x2="136" y2="87"/><line x1="158" y1="57" x2="158" y2="87"/><line x1="180" y1="57" x2="180" y2="87"/></g>\n<text x="210" y="76" font-size="8" fill="#334155">straight wavefronts</text>\n<rect x="40" y="110" width="240" height="20" fill="#f1f5f9" stroke="#94a3b8"/>\n<g fill="#1e293b"><rect x="70" y="110" width="4" height="20"/><rect x="92" y="110" width="4" height="20"/><rect x="114" y="110" width="4" height="20"/><rect x="136" y="110" width="4" height="20"/><rect x="158" y="110" width="4" height="20"/><rect x="180" y="110" width="4" height="20"/></g>\n<text x="210" y="124" font-size="8" fill="#334155">screen (bright/dark bands)</text>\n</svg>',
        },
        {
          caption: "Reflection at a plane mirror: angle of incidence equals angle of reflection, measured from the normal.",
          svg:
            '<svg viewBox="0 0 300 170" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A ray hitting a mirror, with the normal drawn at ninety degrees and equal angles of incidence and reflection">\n<rect x="20" y="120" width="260" height="14" fill="#cbd5e1" stroke="#475569"/>\n<g stroke="#475569"><line x1="30" y1="134" x2="20" y2="144"/><line x1="60" y1="134" x2="50" y2="144"/><line x1="90" y1="134" x2="80" y2="144"/><line x1="120" y1="134" x2="110" y2="144"/><line x1="150" y1="134" x2="140" y2="144"/><line x1="180" y1="134" x2="170" y2="144"/><line x1="210" y1="134" x2="200" y2="144"/><line x1="240" y1="134" x2="230" y2="144"/><line x1="270" y1="134" x2="260" y2="144"/></g>\n<line x1="150" y1="120" x2="150" y2="30" stroke="#64748b" stroke-dasharray="5 4"/>\n<text x="155" y="40" font-size="9" fill="#64748b">normal</text>\n<line x1="60" y1="40" x2="150" y2="120" stroke="#0e7490" stroke-width="2.5" marker-end="url(#in)"/>\n<line x1="150" y1="120" x2="240" y2="40" stroke="#0891b2" stroke-width="2.5" marker-end="url(#out)"/>\n<text x="118" y="95" font-size="10" fill="#0e7490">i</text>\n<text x="178" y="95" font-size="10" fill="#0891b2">r</text>\n<defs><marker id="in" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0e7490"/></marker><marker id="out" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0891b2"/></marker></defs>\n</svg>',
        },
      ],
      keyPoints: [
        "A wavefront joins points in step; a ray shows direction of travel; the gap between wavefronts is one wavelength.",
        "A ripple tank makes water waves visible to study reflection and refraction (a glass plate makes the water shallower, slowing the waves).",
        "Angles are always measured from the normal (90° to the surface).",
        "Law of reflection: angle of incidence = angle of reflection.",
        "Reflection does not change the wave's speed, frequency or wavelength — only its direction.",
      ],
      whyItWorks:
        "Reflection keeps the wave speed the same (same medium), so the geometry of the wavefronts forces the reflected angle to mirror the incident angle.",
      strategies: ["Always draw the normal first", "Measure angles from the normal, not the surface", "In a ripple tank, slower water (shallower) means shorter wavelength"],
    },
    {
      heading: "Refraction and refractive index",
      discovery: {
        problem:
          "A straw in a glass of water looks 'broken' at the surface, and a swimming pool looks shallower than it really is. The light from the straw and the pool floor is perfectly straight — so why does it appear bent?",
        idea: "Light changes speed when it passes from one material into another. A change in speed at an angle makes the ray change direction — this bending is refraction. Your brain assumes light travelled straight, so it 'sees' the object in the wrong place.",
      },
      body:
        "**Refraction** is the change in direction of a wave when it passes from one medium into another, caused by a **change in wave speed**.\n\n- Going into a **denser** (optically slower) medium, e.g. air → glass: the wave **slows down** and bends **towards the normal**.\n- Going into a **less dense** (optically faster) medium, e.g. glass → air: the wave **speeds up** and bends **away from the normal**.\n- A ray hitting the surface **along the normal** (i = 0°) does not bend, though it still changes speed.\n\nThe **refractive index (n)** of a material measures how much it slows light down and bends it:\n\n`n = sin i / sin r`   (i in the first medium, usually air; r in the material)\n\nIt can also be found from the speed of light:\n\n`n = c / v`\n\nwhere c is the speed of light in a vacuum (≈ 3 × 10⁸ m/s) and v is the speed in the material. Because light always slows in a material, **n is always greater than 1** (e.g. glass ≈ 1.5, water ≈ 1.33). A bigger n means more slowing and more bending.\n\n**Ray diagram through a rectangular glass block.** A ray entering the block bends *towards* the normal; when it leaves the far side it bends *away* from the normal by the same amount. Because the two surfaces are parallel, the ray that comes out is **parallel to the ray that went in** — just shifted sideways (a *lateral displacement*).\n\n**Worked example.** Light hits a glass surface from air with angle of incidence 40° and refracts to 25°. Find n. n = sin i / sin r = sin 40° / sin 25° = 0.643 / 0.423 = **1.5** (2 s.f.).",
      diagrams: [
        {
          caption: "A ray through a rectangular glass block: bends towards the normal entering, away leaving; emergent ray is parallel to the incident ray.",
          svg:
            '<svg viewBox="0 0 320 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A light ray passing through a rectangular glass block, bending towards the normal on entry and away on exit, leaving parallel to the original ray but shifted sideways">\n<rect x="90" y="40" width="140" height="100" fill="#bae6fd" stroke="#0369a1"/>\n<text x="160" y="155" font-size="9" text-anchor="middle" fill="#0369a1">glass block</text>\n<line x1="90" y1="70" x2="90" y2="130" stroke="#64748b" stroke-dasharray="4 4"/>\n<line x1="50" y1="55" x2="90" y2="85" stroke="#0e7490" stroke-width="2.5" marker-end="url(#g1)"/>\n<text x="60" y="50" font-size="8" fill="#0e7490">incident</text>\n<line x1="90" y1="85" x2="230" y2="120" stroke="#0e7490" stroke-width="2.5"/>\n<line x1="230" y1="100" x2="230" y2="160" stroke="#64748b" stroke-dasharray="4 4"/>\n<line x1="230" y1="120" x2="275" y2="135" stroke="#0e7490" stroke-width="2.5" marker-end="url(#g2)"/>\n<text x="240" y="150" font-size="8" fill="#0e7490">emergent</text>\n<defs><marker id="g1" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0e7490"/></marker><marker id="g2" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0e7490"/></marker></defs>\n</svg>',
        },
        {
          caption: "Refraction at an air-glass boundary: the ray slows and bends towards the normal entering glass.",
          svg:
            '<svg viewBox="0 0 280 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A light ray passing from air into glass, bending towards the normal as it enters the glass">\n<rect x="20" y="20" width="240" height="80" fill="#eff6ff" stroke="#cbd5e1"/>\n<rect x="20" y="100" width="240" height="80" fill="#bae6fd" stroke="#cbd5e1"/>\n<text x="30" y="38" font-size="10" fill="#475569">air (fast)</text>\n<text x="30" y="170" font-size="10" fill="#0369a1">glass (slow)</text>\n<line x1="140" y1="20" x2="140" y2="180" stroke="#64748b" stroke-dasharray="5 4"/>\n<text x="145" y="32" font-size="9" fill="#64748b">normal</text>\n<line x1="60" y1="40" x2="140" y2="100" stroke="#0e7490" stroke-width="2.5" marker-end="url(#r1)"/>\n<line x1="140" y1="100" x2="190" y2="175" stroke="#0e7490" stroke-width="2.5" marker-end="url(#r2)"/>\n<path d="M140 70 A 30 30 0 0 1 122 86" fill="none" stroke="#dc2626"/>\n<text x="112" y="78" font-size="10" fill="#b91c1c">i</text>\n<path d="M140 130 A 30 30 0 0 0 152 158" fill="none" stroke="#1d4ed8"/>\n<text x="150" y="150" font-size="10" fill="#1d4ed8">r</text>\n<defs><marker id="r1" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0e7490"/></marker><marker id="r2" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0e7490"/></marker></defs>\n</svg>',
        },
      ],
      formulae: ["n = sin i / sin r", "n = c / v", "c ≈ 3 × 10⁸ m/s", "n > 1 always"],
      keyPoints: [
        "Refraction = change of direction caused by change of wave speed.",
        "Into denser medium: slows, bends towards the normal.",
        "Into less dense medium: speeds up, bends away from the normal.",
        "A ray along the normal (i = 0°) changes speed but does not bend.",
        "Through a parallel-sided glass block the emergent ray is parallel to the incident ray (shifted sideways).",
        "n = sin i / sin r = c / v, and n is always > 1.",
      ],
      whyItWorks:
        "Picture the wavefront entering glass at an angle. The end that enters first slows first, so it lags behind the end still in air. The wavefront pivots — like a trolley's wheel hitting mud — turning the whole wave towards the normal.",
      strategies: [
        "Decide if the wave is speeding up or slowing down first, then which way it bends",
        "For n = sin i / sin r, take sin of each angle before dividing",
      ],
    },
    {
      heading: "Total internal reflection and the critical angle",
      discovery: {
        problem:
          "Light usually passes out of glass into air. But shine a laser inside a glass block at a shallow enough angle to the surface and *none* gets out — it reflects perfectly back inside, with no light lost. How can a transparent surface act like a perfect mirror?",
        idea: "Going from glass to air, the ray bends away from the normal. Increase the angle and eventually the refracted ray skims along the surface (r = 90°) — that incidence angle is the critical angle. Go beyond it and the light can no longer escape: it is all reflected. This is total internal reflection.",
      },
      body:
        "When light travels from a denser medium towards a less dense one (e.g. glass → air), it bends *away* from the normal. As you increase the angle of incidence:\n\n1. The refracted ray bends further away from the normal.\n2. At the **critical angle (c)**, the refracted ray travels exactly along the surface (angle of refraction = 90°).\n3. **Beyond** the critical angle, no light escapes — it is **all reflected back inside**. This is **Total Internal Reflection (TIR)**.\n\nThe critical angle links to refractive index by:\n\n`sin c = 1 / n`\n\nTwo conditions are needed for TIR: the light must be going from a **denser to a less dense** medium, AND the angle of incidence must be **greater than the critical angle**.\n\n**Uses of TIR:** optical fibres (carry light/data along a thin glass fibre by bouncing it down the core — used in broadband internet and endoscopes) and 45° prisms (used in periscopes and binoculars to turn light through 90° or 180° with no loss).",
      diagrams: [
        {
          caption: "Total internal reflection inside an optical fibre: light bounces along the core.",
          svg:
            '<svg viewBox="0 0 320 110" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="An optical fibre with a light ray zig-zagging down the core by total internal reflection">\n<rect x="10" y="35" width="300" height="40" fill="#bae6fd" stroke="#0369a1"/>\n<text x="160" y="100" font-size="10" text-anchor="middle" fill="#334155">core (light bounces by TIR, none escapes)</text>\n<polyline points="10,40 70,70 130,40 190,70 250,40 310,70" fill="none" stroke="#0e7490" stroke-width="2.5" marker-end="url(#t)"/>\n<defs><marker id="t" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#0e7490"/></marker></defs>\n</svg>',
        },
      ],
      formulae: ["sin c = 1 / n", "TIR needs: dense → less dense AND i > critical angle c"],
      keyPoints: [
        "Critical angle c: angle of incidence giving refraction at exactly 90°.",
        "Beyond c, all light is reflected back inside (TIR).",
        "sin c = 1/n.",
        "TIR needs denser → less dense medium and i > c.",
        "Uses: optical fibres (data, endoscopes) and prisms (periscopes, binoculars).",
      ],
      whyItWorks:
        "As i grows, r grows faster (bending away from the normal) until r hits its maximum of 90°. There is no angle left for the ray to refract into, so the surface reflects 100% of the light instead.",
      strategies: [
        "Check both TIR conditions before claiming it happens",
        "Use sin c = 1/n: a higher n gives a smaller critical angle",
      ],
    },
    {
      heading: "The electromagnetic spectrum",
      body:
        "**Electromagnetic (EM) waves** are transverse waves that travel through a vacuum at the speed of light, c ≈ **3 × 10⁸ m/s**. They form a continuous **spectrum**, ordered by wavelength and frequency:\n\n`Radio — Microwave — Infrared — Visible — Ultraviolet — X-ray — Gamma`\n\nFrom radio to gamma, **wavelength decreases** and **frequency (and energy) increases**. Visible light is the only part our eyes detect, running red → orange → yellow → green → blue → indigo → violet (red has the longest wavelength, violet the shortest).\n\n**Uses:**\n\n- **Radio** — broadcasting TV and radio signals.\n- **Microwave** — cooking; satellite and mobile-phone communication.\n- **Infrared** — remote controls, thermal imaging, optical fibre signals, heaters/grills.\n- **Visible** — seeing, photography, illumination.\n- **Ultraviolet (UV)** — security marking, sterilising water, fluorescent lamps, tanning.\n- **X-ray** — medical images of bones, airport security scanning.\n- **Gamma** — sterilising medical equipment and food, treating (and detecting) cancer.\n\n**Dangers** (rising with frequency/energy): **microwaves** can heat the water in body cells (internal heating); **infrared** causes skin burns; **UV** damages skin (premature ageing and skin cancer) and the eyes (can cause blindness); **X-rays** and **gamma** are *ionising* — they carry enough energy to knock electrons off atoms, damaging cells, causing mutations and cancer. The higher the frequency, the higher the energy and the greater the danger.\n\n**The visible spectrum.** Visible light is the narrow band our eyes detect, roughly **400 nm to 700 nm** (1 nm = 1 × 10⁻⁹ m). Splitting white light with a prism gives the colours in order of decreasing wavelength:\n\n`Red (longest λ ≈ 700 nm) → Orange → Yellow → Green → Blue → Indigo → Violet (shortest λ ≈ 400 nm)`\n\nSo **red light has the longest wavelength and lowest frequency**, and **violet has the shortest wavelength and highest frequency**. Just beyond red is infrared; just beyond violet is ultraviolet.",
      diagrams: [
        {
          caption: "The EM spectrum from radio (long wavelength, low frequency) to gamma (short wavelength, high frequency).",
          svg:
            '<svg viewBox="0 0 360 110" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="The electromagnetic spectrum strip from radio to gamma with wavelength decreasing and frequency increasing to the right">\n<rect x="10" y="30" width="49" height="30" fill="#fca5a5"/><rect x="59" y="30" width="49" height="30" fill="#fdba74"/><rect x="108" y="30" width="49" height="30" fill="#fde047"/><rect x="157" y="30" width="49" height="30" fill="#86efac"/><rect x="206" y="30" width="49" height="30" fill="#7dd3fc"/><rect x="255" y="30" width="49" height="30" fill="#a5b4fc"/><rect x="304" y="30" width="46" height="30" fill="#d8b4fe"/>\n<g font-size="7.5" text-anchor="middle" fill="#1e293b">\n<text x="34" y="49">Radio</text><text x="83" y="49">Micro</text><text x="132" y="49">IR</text><text x="181" y="49">Visible</text><text x="230" y="49">UV</text><text x="279" y="49">X-ray</text><text x="327" y="49">Gamma</text>\n</g>\n<text x="12" y="22" font-size="9" fill="#334155">long wavelength, low frequency</text>\n<text x="348" y="22" font-size="9" text-anchor="end" fill="#334155">short wavelength, high frequency</text>\n<line x1="10" y1="72" x2="350" y2="72" stroke="#1e293b" stroke-width="1.5" marker-end="url(#fr)"/>\n<text x="180" y="86" font-size="8" text-anchor="middle" fill="#334155">frequency / energy increases this way</text>\n<defs><marker id="fr" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#1e293b"/></marker></defs>\n</svg>',
        },
        {
          caption: "The visible spectrum: red has the longest wavelength (~700 nm), violet the shortest (~400 nm).",
          svg:
            '<svg viewBox="0 0 320 90" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="The visible spectrum from red on the left with long wavelength to violet on the right with short wavelength">\n<rect x="20" y="25" width="40" height="30" fill="#ef4444"/><rect x="60" y="25" width="40" height="30" fill="#f97316"/><rect x="100" y="25" width="40" height="30" fill="#facc15"/><rect x="140" y="25" width="40" height="30" fill="#22c55e"/><rect x="180" y="25" width="40" height="30" fill="#3b82f6"/><rect x="220" y="25" width="40" height="30" fill="#4338ca"/><rect x="260" y="25" width="40" height="30" fill="#7c3aed"/>\n<text x="20" y="18" font-size="8" fill="#334155">red ~700 nm (long)</text>\n<text x="300" y="18" font-size="8" text-anchor="end" fill="#334155">violet ~400 nm (short)</text>\n<g font-size="7" text-anchor="middle" fill="#ffffff"><text x="40" y="44">R</text><text x="80" y="44">O</text><text x="120" y="44">Y</text><text x="160" y="44">G</text><text x="200" y="44">B</text><text x="240" y="44">I</text><text x="280" y="44">V</text></g>\n<text x="160" y="74" font-size="8" text-anchor="middle" fill="#334155">wavelength decreases, frequency increases</text>\n</svg>',
        },
      ],
      formulae: ["all EM waves: v = c ≈ 3 × 10⁸ m/s in a vacuum", "v = f λ still applies", "visible light ≈ 400 nm (violet) to 700 nm (red)"],
      keyPoints: [
        "Order (long→short λ): Radio, Micro, IR, Visible, UV, X-ray, Gamma.",
        "Towards gamma: wavelength falls, frequency and energy rise.",
        "All EM waves are transverse and travel at c (3 × 10⁸ m/s) in a vacuum.",
        "Visible colours (long→short λ): Red, Orange, Yellow, Green, Blue, Indigo, Violet.",
        "Each band has uses AND dangers; dangers grow with frequency. UV, X-ray and gamma are most harmful (X-ray/gamma are ionising).",
      ],
      whyItWorks:
        "All EM waves are oscillating electric and magnetic fields that regenerate each other, so they need no medium and all move at the same speed c. Since v = f λ is fixed, frequency and wavelength trade off across the spectrum.",
      strategies: [
        "Memorise the order with a mnemonic (e.g. 'Raging Martians Invaded Venus Using X-ray Guns')",
        "Match each band to one use and one danger",
      ],
    },
    {
      heading: "Sound waves",
      discovery: {
        problem:
          "In sci-fi films, spaceship battles roar with explosions. But astronauts on real spacewalks must talk by radio even when floating side by side. Why can't they just shout to each other in space?",
        idea: "Sound is a longitudinal wave that needs a medium — particles to be squashed and stretched. Space is a near-vacuum with almost no particles, so there is nothing to carry the sound. No medium, no sound.",
      },
      body:
        "**Sound** is a **longitudinal** wave made of compressions and rarefactions travelling through a medium (solid, liquid or gas). Sound **cannot travel through a vacuum** because it needs particles.\n\nSound travels **fastest in solids**, slower in liquids, and slowest in gases (particles are closest together in solids, so vibrations pass on quickest). In air it travels at about **340 m/s**.\n\nThe wave's properties map onto what we hear:\n\n- **Frequency ↔ pitch.** Higher frequency = higher pitch.\n- **Amplitude ↔ loudness.** Bigger amplitude = louder sound.\n\nThe normal **human hearing range is about 20 Hz to 20 000 Hz** (20 kHz). Below 20 Hz is *infrasound*; above 20 kHz is *ultrasound*. The wave equation v = f λ applies to sound just as it does to other waves.\n\n**Measuring the speed of sound in air.** A simple method uses an **echo**: stand a measured distance d from a large flat wall, clap, and time how long the echo takes to return. The sound travels to the wall and back (a distance 2d), so speed = distance ÷ time = 2d ÷ t. Averaging many claps reduces error. *Example:* d = 50 m, echo after 0.29 s → v = (2 × 50) ÷ 0.29 ≈ 340 m/s. A more accurate lab method uses **two microphones** a known distance apart connected to a timer (or oscilloscope): a sound is made and the timer measures the tiny delay between the microphones picking it up, giving v = distance ÷ time.\n\n**Oscilloscope (CRO) traces.** A microphone changes sound into an electrical signal which an oscilloscope displays as a wave on a screen. The trace lets you compare sounds:\n\n- **Louder sound → taller trace** (bigger amplitude).\n- **Higher pitch → waves closer together** (higher frequency, shorter period on screen).\n\nReading off the time for one cycle gives the period T, and f = 1/T gives the frequency.",
      diagrams: [
        {
          caption: "Oscilloscope traces: a louder sound has a bigger amplitude; a higher-pitched sound has more waves (higher frequency).",
          svg:
            '<svg viewBox="0 0 320 130" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two oscilloscope traces compared, one with larger amplitude for a louder sound and one with more cycles for a higher pitch">\n<rect x="10" y="10" width="140" height="55" fill="#0f172a" stroke="#334155"/>\n<path d="M10 37 C25 12 40 12 55 37 C70 62 85 62 100 37 C115 12 130 12 145 37" fill="none" stroke="#22d3ee" stroke-width="2"/>\n<text x="80" y="80" font-size="8" text-anchor="middle" fill="#334155">louder (bigger amplitude)</text>\n<rect x="170" y="10" width="140" height="55" fill="#0f172a" stroke="#334155"/>\n<path d="M170 37 C177 22 184 22 191 37 C198 52 205 52 212 37 C219 22 226 22 233 37 C240 52 247 52 254 37 C261 22 268 22 275 37 C282 52 289 52 296 37 C303 28 307 28 310 37" fill="none" stroke="#a3e635" stroke-width="2"/>\n<text x="240" y="80" font-size="8" text-anchor="middle" fill="#334155">higher pitch (higher frequency)</text>\n</svg>',
        },
      ],
      formulae: ["v = f λ (applies to sound)", "speed of sound in air ≈ 340 m/s", "echo method: v = 2d / t", "human hearing range ≈ 20 Hz – 20 000 Hz"],
      keyPoints: [
        "Sound is longitudinal and needs a medium (no sound in a vacuum).",
        "Fastest in solids, slowest in gases; in air ≈ 340 m/s.",
        "Frequency → pitch; amplitude → loudness.",
        "Human hearing range ≈ 20 Hz to 20 000 Hz.",
        "Measure speed by echo (v = 2d/t) or two microphones and a timer.",
        "On an oscilloscope: taller trace = louder; waves closer together = higher pitch.",
      ],
      whyItWorks:
        "A vibrating source pushes nearby particles together (compression); they push the next layer and bounce back, leaving a rarefaction. This squash-stretch pattern passes the energy on — but only if particles are present to be pushed.",
      strategies: ["Convert pitch/loudness questions to frequency/amplitude", "Remember solids transmit sound fastest because particles are closest"],
    },
    {
      heading: "Converging lenses and ray diagrams",
      body:
        "A **converging (convex) lens** is thicker in the middle and bends parallel rays inwards so they meet at the **principal focus (F)**. The distance from the lens to F is the **focal length**.\n\nTo find the image, draw two rays from the top of the object:\n\n1. A ray **parallel** to the axis, which refracts through the **focal point F** on the far side.\n2. A ray straight through the **centre of the lens**, which carries on undeviated.\n\nWhere the rays meet is the top of the image.\n\n**Real vs virtual images:**\n\n- A **real image** forms where rays actually cross. It can be projected on a screen and is **inverted** (upside down). This happens when the object is **beyond F** (e.g. camera, eye, projector).\n- A **virtual image** forms when the object is **inside F**: the refracted rays diverge, so you trace them *backwards* (dashed lines) to where they appear to come from. It is **upright and magnified** and **cannot** be put on a screen — this is the **magnifying glass**.\n\n**Magnification.** How much bigger (or smaller) the image is than the object is the **magnification**:\n\n`magnification = image height / object height`\n\nMagnification has **no unit** (it is a ratio). A magnification greater than 1 means the image is enlarged; less than 1 means it is smaller. *Worked example:* an object 2 cm tall gives an image 6 cm tall. Magnification = 6 / 2 = **3** (the image is 3× the size of the object).\n\n**Summary of object position vs image** (for a converging lens):\n\n- Object **beyond 2F** → real, inverted, *smaller* image (the camera).\n- Object **between F and 2F** → real, inverted, *larger* image (the projector).\n- Object **inside F** → virtual, upright, *larger* image (the magnifying glass).",
      diagrams: [
        {
          caption: "Converging lens forming a real, inverted image of an object placed beyond F.",
          svg:
            '<svg viewBox="0 0 360 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A converging lens ray diagram with an object beyond the focal point forming a smaller inverted real image on the far side">\n<line x1="10" y1="90" x2="350" y2="90" stroke="#94a3b8"/>\n<ellipse cx="180" cy="90" rx="12" ry="62" fill="#bae6fd" stroke="#0369a1"/>\n<circle cx="130" cy="90" r="3" fill="#1e293b"/><text x="120" y="103" font-size="9" fill="#334155">F</text>\n<circle cx="230" cy="90" r="3" fill="#1e293b"/><text x="228" y="103" font-size="9" fill="#334155">F</text>\n<line x1="70" y1="90" x2="70" y2="40" stroke="#0e7490" stroke-width="2.5" marker-end="url(#ob)"/>\n<text x="58" y="36" font-size="9" fill="#0e7490">object</text>\n<line x1="70" y1="40" x2="180" y2="40" stroke="#dc2626" stroke-width="1.5"/>\n<line x1="180" y1="40" x2="280" y2="125" stroke="#dc2626" stroke-width="1.5" marker-end="url(#ry)"/>\n<line x1="70" y1="40" x2="280" y2="125" stroke="#1d4ed8" stroke-width="1.5" marker-end="url(#ry2)"/>\n<line x1="270" y1="90" x2="270" y2="123" stroke="#16a34a" stroke-width="2.5" marker-end="url(#im)"/>\n<text x="276" y="118" font-size="9" fill="#15803d">image (real, inverted)</text>\n<defs><marker id="ob" markerWidth="8" markerHeight="8" refX="4" refY="1" orient="auto"><path d="M0 6 L4 0 L8 6 z" fill="#0e7490"/></marker><marker id="im" markerWidth="8" markerHeight="8" refX="4" refY="6" orient="auto"><path d="M0 0 L4 6 L8 0 z" fill="#16a34a"/></marker><marker id="ry" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#dc2626"/></marker><marker id="ry2" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#1d4ed8"/></marker></defs>\n</svg>',
        },
        {
          caption: "Magnifying glass: object inside F gives an upright, magnified, virtual image (dashed rays traced back).",
          svg:
            '<svg viewBox="0 0 360 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A converging lens with an object inside the focal length, the refracted rays traced back as dashed lines to form an upright magnified virtual image on the same side">\n<line x1="10" y1="110" x2="350" y2="110" stroke="#94a3b8"/>\n<ellipse cx="200" cy="110" rx="12" ry="65" fill="#bae6fd" stroke="#0369a1"/>\n<circle cx="120" cy="110" r="3" fill="#1e293b"/><text x="110" y="124" font-size="9" fill="#334155">F</text>\n<circle cx="280" cy="110" r="3" fill="#1e293b"/><text x="278" y="124" font-size="9" fill="#334155">F</text>\n<line x1="165" y1="110" x2="165" y2="75" stroke="#0e7490" stroke-width="2.5" marker-end="url(#ob2)"/>\n<text x="150" y="71" font-size="8" fill="#0e7490">object</text>\n<line x1="165" y1="75" x2="200" y2="75" stroke="#dc2626" stroke-width="1.5"/>\n<line x1="200" y1="75" x2="330" y2="40" stroke="#dc2626" stroke-width="1.5" marker-end="url(#ry3)"/>\n<line x1="200" y1="75" x2="60" y2="48" stroke="#dc2626" stroke-width="1.2" stroke-dasharray="5 4"/>\n<line x1="165" y1="75" x2="330" y2="20" stroke="#1d4ed8" stroke-width="1.5" marker-end="url(#ry4)"/>\n<line x1="165" y1="75" x2="60" y2="48" stroke="#1d4ed8" stroke-width="1.2" stroke-dasharray="5 4"/>\n<line x1="60" y1="110" x2="60" y2="48" stroke="#16a34a" stroke-width="2.5" marker-end="url(#im2)"/>\n<text x="20" y="44" font-size="8" fill="#15803d">virtual image (upright, magnified)</text>\n<defs><marker id="ob2" markerWidth="8" markerHeight="8" refX="4" refY="1" orient="auto"><path d="M0 6 L4 0 L8 6 z" fill="#0e7490"/></marker><marker id="im2" markerWidth="8" markerHeight="8" refX="4" refY="1" orient="auto"><path d="M0 6 L4 0 L8 6 z" fill="#16a34a"/></marker><marker id="ry3" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#dc2626"/></marker><marker id="ry4" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 z" fill="#1d4ed8"/></marker></defs>\n</svg>',
        },
      ],
      formulae: ["Ray 1: parallel ray → refracts through far focal point F", "Ray 2: ray through lens centre → undeviated", "magnification = image height / object height (no unit)"],
      keyPoints: [
        "Converging (convex) lens brings parallel rays to the principal focus F; lens-to-F distance = focal length.",
        "Draw the parallel-then-through-F ray and the straight-through-centre ray; they cross at the image.",
        "Object beyond F → real, inverted image (can be on a screen).",
        "Object inside F → virtual, upright, magnified image (magnifying glass).",
        "magnification = image height / object height (a ratio, no unit).",
      ],
      whyItWorks:
        "The lens refracts light twice (entering and leaving the glass). Its curved shape bends rays by just the right amount to bring parallel rays together at F, and to form an image of any object point where its rays reconverge.",
      strategies: [
        "Always draw both standard rays from the top of the object",
        "If rays diverge after the lens, trace them back — the image is virtual",
      ],
    },
  ],
  learn: {
    bigIdea:
      "Waves transfer energy without transferring matter. Describe them with amplitude, wavelength, frequency and period, link them with v = f λ, and explain how they reflect, refract and totally internally reflect. The EM spectrum, sound and lenses are all the same wave physics applied.",
    mustKnow: [
      "Transverse: vibrations at 90° to travel; longitudinal: vibrations along travel (sound).",
      "v = f λ and f = 1/T — learn the rearrangements.",
      "Law of reflection: angle of incidence = angle of reflection (from the normal).",
      "Refraction is bending due to a speed change; n = sin i / sin r = c/v, and n > 1.",
      "Total internal reflection needs dense→less dense AND i > critical angle, with sin c = 1/n.",
      "EM order (long→short λ): Radio, Micro, IR, Visible, UV, X-ray, Gamma — all travel at c.",
      "Sound is longitudinal, needs a medium; frequency↔pitch, amplitude↔loudness, range 20 Hz–20 kHz.",
      "Converging lens: object beyond F → real inverted image; inside F → virtual upright magnified image; magnification = image height / object height.",
      "Each EM band has a use AND a danger; visible colours red→violet run long→short wavelength.",
    ],
    keywords: [
      { term: "Transverse wave", definition: "A wave whose vibrations are at right angles (90°) to the direction of energy transfer." },
      { term: "Longitudinal wave", definition: "A wave whose vibrations are parallel to the direction of energy transfer, forming compressions and rarefactions." },
      { term: "Amplitude", definition: "The maximum displacement of a particle from its rest position; linked to the wave's energy." },
      { term: "Wavelength (λ)", definition: "The distance for one complete wave, e.g. crest to crest, measured in metres." },
      { term: "Frequency (f)", definition: "The number of complete waves passing a point per second, measured in hertz (Hz)." },
      { term: "Period (T)", definition: "The time taken for one complete wave to pass a point; T = 1/f." },
      { term: "Refraction", definition: "The change in direction of a wave when it changes speed on passing into a new medium." },
      { term: "Refractive index (n)", definition: "A measure of how much a material slows and bends light: n = sin i / sin r = c/v, always greater than 1." },
      { term: "Critical angle (c)", definition: "The angle of incidence in the denser medium for which the refracted ray travels along the surface; sin c = 1/n." },
      { term: "Total internal reflection", definition: "When light hitting a boundary from a denser medium at an angle greater than the critical angle is entirely reflected back." },
    ],
    flashcards: [
      { front: "State the wave equation and the meaning of each symbol.", back: "v = f λ: wave speed (m/s) = frequency (Hz) × wavelength (m)." },
      { front: "What is the difference between a transverse and a longitudinal wave?", back: "Transverse vibrates at 90° to travel direction; longitudinal vibrates along the travel direction (compressions and rarefactions)." },
      { front: "Give the two equations for refractive index.", back: "n = sin i / sin r and n = c / v (always n > 1)." },
      { front: "What two conditions are needed for total internal reflection?", back: "Light going from a denser to a less dense medium AND angle of incidence greater than the critical angle." },
      { front: "List the EM spectrum from longest to shortest wavelength.", back: "Radio, Microwave, Infrared, Visible, Ultraviolet, X-ray, Gamma." },
      { front: "Why can't sound travel through space?", back: "Sound is longitudinal and needs particles (a medium); space is a vacuum with almost none." },
    ],
  },
  quiz: {
    mcq: [
      {
        id: "wv-mcq-q01",
        question: "A wave transfers…",
        options: ["matter but not energy", "energy but not matter", "both energy and matter", "neither energy nor matter"],
        answerIndex: 1,
        explanation: "A wave carries energy from place to place while the particles of the medium only vibrate about fixed positions — no net matter is transferred.",
        guideRef: "What is a wave? Transverse vs longitudinal",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q02",
        question: "In a transverse wave the vibrations are…",
        options: ["along the direction of travel", "at right angles to the direction of travel", "in circles", "stationary"],
        answerIndex: 1,
        explanation: "Transverse means the oscillations are perpendicular (90°) to the direction the wave's energy travels.",
        guideRef: "What is a wave? Transverse vs longitudinal",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q03",
        question: "Which of these is a longitudinal wave?",
        options: ["A water wave", "A light wave", "A sound wave", "A radio wave"],
        answerIndex: 2,
        explanation: "Sound is longitudinal (compressions and rarefactions). Water and all EM waves (light, radio) are transverse.",
        guideRef: "Sound waves",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q04",
        question: "The amplitude of a wave is the…",
        options: ["distance between two crests", "number of waves per second", "maximum displacement from rest", "time for one wave to pass"],
        answerIndex: 2,
        explanation: "Amplitude is the maximum displacement of a particle from its rest position and is linked to the wave's energy.",
        guideRef: "Describing waves: amplitude, wavelength, frequency, period",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q05",
        question: "The unit of frequency is the…",
        options: ["metre", "second", "hertz", "newton"],
        answerIndex: 2,
        explanation: "Frequency is measured in hertz (Hz), where 1 Hz = 1 complete wave per second.",
        guideRef: "Describing waves: amplitude, wavelength, frequency, period",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q06",
        question: "A wave has a period of 0.25 s. Its frequency is…",
        options: ["0.25 Hz", "2 Hz", "4 Hz", "25 Hz"],
        answerIndex: 2,
        explanation: "f = 1/T = 1/0.25 = 4 Hz.",
        guideRef: "Describing waves: amplitude, wavelength, frequency, period",
        difficulty: "core",
        hints: ["Which equation links frequency and period?", "f = 1/T.", "1 ÷ 0.25 = ?"],
        strategy: "Pick the right formula",
      },
      {
        id: "wv-mcq-q07",
        question: "A wave has frequency 50 Hz and wavelength 6 m. Its speed is…",
        options: ["8.3 m/s", "44 m/s", "300 m/s", "56 m/s"],
        answerIndex: 2,
        explanation: "v = f λ = 50 × 6 = 300 m/s.",
        guideRef: "The wave equation v = f λ",
        difficulty: "core",
        hints: ["Use the wave equation.", "v = f λ.", "50 × 6 = ?"],
        strategy: "Substitute into v = f λ",
      },
      {
        id: "wv-mcq-q08",
        question: "A wave travels at 320 m/s with a frequency of 80 Hz. Its wavelength is…",
        options: ["4 m", "0.25 m", "25 600 m", "40 m"],
        answerIndex: 0,
        explanation: "λ = v/f = 320/80 = 4 m.",
        guideRef: "The wave equation v = f λ",
        difficulty: "core",
        hints: ["Rearrange v = f λ to make λ the subject.", "λ = v/f.", "320 ÷ 80 = ?"],
        strategy: "Rearrange before substituting",
      },
      {
        id: "wv-mcq-q09",
        question: "In the law of reflection, the angle of incidence is measured between the ray and the…",
        options: ["surface of the mirror", "normal", "reflected ray", "horizontal"],
        answerIndex: 1,
        explanation: "Both the angle of incidence and angle of reflection are measured from the normal (the line at 90° to the surface).",
        guideRef: "Wavefronts, reflection and the law of reflection",
        difficulty: "core",
        hints: ["Angles in optics are not measured from the surface.", "What line is drawn at 90° to the surface?", "It's called the normal."],
      },
      {
        id: "wv-mcq-q10",
        question: "A ray of light enters a glass block from air. As it enters the glass it…",
        options: ["speeds up and bends away from the normal", "slows down and bends towards the normal", "slows down and bends away from the normal", "keeps the same speed and direction"],
        answerIndex: 1,
        explanation: "Glass is optically denser, so light slows down and bends towards the normal on entering.",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["Is glass faster or slower for light than air?", "Slowing into a denser medium bends the ray which way?", "Towards the normal."],
        strategy: "Decide speed change first, then bend direction",
      },
      {
        id: "wv-mcq-q11",
        question: "The refractive index of a material is given by…",
        options: ["sin r / sin i", "sin i / sin r", "sin i × sin r", "sin i + sin r"],
        answerIndex: 1,
        explanation: "n = sin i / sin r, with i the angle in air (or first medium) and r the angle in the material.",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["The incidence angle goes on top.", "n = sin i / sin r.", "Take the sine of each angle, then divide."],
      },
      {
        id: "wv-mcq-q12",
        question: "Light travels at 2.0 × 10⁸ m/s in a transparent plastic. Using c = 3.0 × 10⁸ m/s, the refractive index is…",
        options: ["0.67", "1.5", "2.0", "6.0"],
        answerIndex: 1,
        explanation: "n = c/v = (3.0 × 10⁸)/(2.0 × 10⁸) = 1.5.",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["Which formula uses speeds?", "n = c/v.", "3.0 ÷ 2.0 = ?"],
        strategy: "Use n = c/v",
      },
      {
        id: "wv-mcq-q13",
        question: "Total internal reflection can only happen when light travels from…",
        options: ["a less dense to a denser medium", "a denser to a less dense medium", "air into glass", "a vacuum into glass"],
        answerIndex: 1,
        explanation: "TIR needs light going from a denser (slower) medium to a less dense (faster) one, with an angle of incidence above the critical angle.",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "core",
        hints: ["Which direction lets the ray bend away from the normal?", "It must be able to refract to 90° first.", "Dense → less dense."],
      },
      {
        id: "wv-mcq-q14",
        question: "A material has a refractive index of 2.0. Its critical angle is the angle whose sine is…",
        options: ["2.0", "0.5", "1.0", "0.25"],
        answerIndex: 1,
        explanation: "sin c = 1/n = 1/2.0 = 0.5 (so c = 30°).",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "core",
        hints: ["Which equation gives the critical angle?", "sin c = 1/n.", "1 ÷ 2.0 = ?"],
        strategy: "Use sin c = 1/n",
      },
      {
        id: "wv-mcq-q15",
        question: "Optical fibres carry light signals by using…",
        options: ["refraction out of the fibre", "diffraction", "total internal reflection", "absorption"],
        answerIndex: 2,
        explanation: "Light is kept inside the core by repeated total internal reflection, so very little escapes along the way.",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q16",
        question: "Which part of the EM spectrum has the longest wavelength?",
        options: ["Gamma rays", "X-rays", "Radio waves", "Ultraviolet"],
        answerIndex: 2,
        explanation: "Radio waves have the longest wavelength (and lowest frequency); gamma rays have the shortest wavelength.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q17",
        question: "Which is the correct order of the EM spectrum from longest to shortest wavelength?",
        options: [
          "Radio, Infrared, Microwave, Visible, UV, X-ray, Gamma",
          "Radio, Microwave, Infrared, Visible, UV, X-ray, Gamma",
          "Gamma, X-ray, UV, Visible, Infrared, Microwave, Radio",
          "Microwave, Radio, Infrared, Visible, X-ray, UV, Gamma",
        ],
        answerIndex: 1,
        explanation: "From longest to shortest: Radio, Microwave, Infrared, Visible, Ultraviolet, X-ray, Gamma.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["Radio is longest, gamma is shortest.", "Microwave comes just after radio.", "Infrared sits just below visible light."],
        strategy: "Use a mnemonic for the order",
      },
      {
        id: "wv-mcq-q18",
        question: "Which type of EM wave is commonly used in TV remote controls?",
        options: ["Gamma rays", "Infrared", "Microwaves", "X-rays"],
        answerIndex: 1,
        explanation: "Remote controls send short pulses of infrared radiation to the device.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q19",
        question: "All electromagnetic waves travel through a vacuum at…",
        options: ["340 m/s", "the same speed, about 3 × 10⁸ m/s", "different speeds depending on frequency", "the speed of sound"],
        answerIndex: 1,
        explanation: "In a vacuum every EM wave travels at the speed of light, c ≈ 3 × 10⁸ m/s, regardless of frequency.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["Do radio and gamma travel at the same speed in space?", "Yes — the speed of light.", "c ≈ 3 × 10⁸ m/s."],
      },
      {
        id: "wv-mcq-q20",
        question: "The pitch of a sound is determined by its…",
        options: ["amplitude", "frequency", "speed", "wavelength only"],
        answerIndex: 1,
        explanation: "Higher frequency gives higher pitch; amplitude controls loudness instead.",
        guideRef: "Sound waves",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q21",
        question: "The approximate range of human hearing is…",
        options: ["2 Hz to 200 Hz", "20 Hz to 20 000 Hz", "200 Hz to 2000 Hz", "20 Hz to 200 000 Hz"],
        answerIndex: 1,
        explanation: "A healthy young person can typically hear from about 20 Hz up to 20 000 Hz (20 kHz).",
        guideRef: "Sound waves",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q22",
        question: "Sound generally travels fastest in…",
        options: ["a vacuum", "a gas", "a liquid", "a solid"],
        answerIndex: 3,
        explanation: "Particles are closest together in solids, so the vibrations are passed on quickest — sound is fastest in solids and cannot travel in a vacuum.",
        guideRef: "Sound waves",
        difficulty: "core",
        hints: ["Sound needs particles — which state has them closest?", "Closer particles pass vibrations faster.", "Solids beat liquids and gases."],
      },
      {
        id: "wv-mcq-q23",
        question: "An object is placed beyond the principal focus F of a converging lens. The image formed is…",
        options: ["virtual, upright and magnified", "real and inverted", "always the same size as the object", "never formed"],
        answerIndex: 1,
        explanation: "With the object beyond F the refracted rays actually cross, forming a real, inverted image that can be projected on a screen.",
        guideRef: "Converging lenses and ray diagrams",
        difficulty: "core",
        hints: ["Do the rays actually cross, or only appear to?", "Crossing rays make a real image.", "Real images from a single lens are inverted."],
      },
      {
        id: "wv-mcq-q24",
        question: "A converging lens used as a magnifying glass produces a virtual, upright, magnified image. This happens when the object is…",
        options: ["beyond 2F", "exactly at F", "inside the focal length (between F and the lens)", "at infinity"],
        answerIndex: 2,
        explanation: "When the object is inside F, the refracted rays diverge; tracing them back gives an upright, magnified virtual image — the magnifying-glass effect.",
        guideRef: "Converging lenses and ray diagrams",
        difficulty: "challenge",
        hints: ["A magnifying glass is held close to the object.", "If rays diverge after the lens the image is virtual.", "The object must be inside the focal length."],
        strategy: "Link image type to object position",
      },
      {
        id: "wv-mcq-q25",
        question: "A wave passes from deep water into shallow water, where it slows down. Its frequency stays the same. Therefore its wavelength…",
        options: ["increases", "decreases", "stays the same", "becomes zero"],
        answerIndex: 1,
        explanation: "Frequency is set by the source and is unchanged. Since v = f λ and v decreases while f is constant, λ must decrease.",
        guideRef: "The wave equation v = f λ",
        difficulty: "challenge",
        hints: ["Which quantity is fixed by the source?", "Frequency stays the same across a boundary.", "If v falls and f is fixed in v = f λ, what must λ do?"],
        strategy: "Hold the constant quantity fixed in v = f λ",
      },
      {
        id: "wv-mcq-q26",
        question: "Light goes from glass (n = 1.5) towards air and hits the boundary at 50°. The critical angle for this glass is about 42°. The light will…",
        options: ["refract and pass into the air, bending towards the normal", "refract and pass into the air, bending away from the normal", "be totally internally reflected", "split equally between reflection and refraction"],
        answerIndex: 2,
        explanation: "It is going from a denser to a less dense medium and 50° is greater than the critical angle of 42°, so total internal reflection occurs and no light escapes.",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "challenge",
        hints: ["Check both TIR conditions.", "Is it dense → less dense? Yes.", "Is 50° greater than the 42° critical angle?"],
        strategy: "Test both TIR conditions",
      },
      {
        id: "wv-mcq-q27",
        question: "A ripple tank is used to study water waves because it…",
        options: ["makes the waves travel at the speed of light", "makes waves large and slow enough to see and measure", "turns water waves into sound", "removes the need for a medium"],
        answerIndex: 1,
        explanation: "A ripple tank makes water waves visible (a lamp projects crests and troughs onto a screen) so reflection and refraction can be observed and measured.",
        guideRef: "Wavefronts, the ripple tank, reflection and the law of reflection",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q28",
        question: "In a ripple tank, water waves move from a deep region over a glass plate where the water is shallower. There they travel more slowly. The wavelength of the waves in the shallow water…",
        options: ["increases", "decreases", "stays the same", "becomes zero"],
        answerIndex: 1,
        explanation: "Frequency is set by the dipper and is unchanged. As v decreases (slower in shallow water) with f constant, v = f λ means λ must decrease.",
        guideRef: "Wavefronts, the ripple tank, reflection and the law of reflection",
        difficulty: "challenge",
        hints: ["Frequency is fixed by the vibrating bar.", "The waves slow down in shallow water.", "In v = f λ with f fixed and v smaller, λ must do what?"],
        strategy: "Hold the constant quantity fixed in v = f λ",
      },
      {
        id: "wv-mcq-q29",
        question: "When a wave is reflected, which property changes?",
        options: ["Its speed", "Its frequency", "Its wavelength", "Its direction"],
        answerIndex: 3,
        explanation: "Reflection stays in the same medium, so speed, frequency and wavelength are unchanged — only the direction of travel changes.",
        guideRef: "Wavefronts, the ripple tank, reflection and the law of reflection",
        difficulty: "core",
        hints: ["Is the wave still in the same medium after reflecting?", "Same medium means same speed.", "Only one of these must change when a wave bounces."],
      },
      {
        id: "wv-mcq-q30",
        question: "A ray of light enters and then leaves a rectangular glass block. Compared with the ray that entered, the ray that emerges is…",
        options: ["bent further towards the normal", "travelling in a completely new direction", "parallel to the entering ray but shifted sideways", "reflected straight back"],
        answerIndex: 2,
        explanation: "The ray bends towards the normal on entry and away by the same amount on exit; because the two faces are parallel, the emergent ray is parallel to the incident ray, just displaced sideways.",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["The two faces of the block are parallel.", "It bends one way entering and the opposite way leaving.", "Equal-and-opposite bends keep it parallel."],
      },
      {
        id: "wv-mcq-q31",
        question: "Light enters glass from air with an angle of incidence of 40°, refracting to 25°. Using sin 40° = 0.643 and sin 25° = 0.423, the refractive index is about…",
        options: ["0.66", "1.5", "1.6", "0.62"],
        answerIndex: 1,
        explanation: "n = sin i / sin r = 0.643 / 0.423 = 1.5 (2 s.f.).",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["Use n = sin i / sin r.", "Incidence angle on top.", "0.643 ÷ 0.423 = ?"],
        strategy: "Use n = sin i / sin r",
      },
      {
        id: "wv-mcq-q32",
        question: "Reflecting prisms in a periscope or binoculars turn light using…",
        options: ["refraction at the critical angle", "total internal reflection", "diffraction", "absorption and re-emission"],
        answerIndex: 1,
        explanation: "Light hits the sloping face of a 45° prism at more than the critical angle for glass, so it is totally internally reflected and turned through 90° (or 180°) with very little loss.",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "core",
        hints: ["The light strikes the prism face at 45°.", "42° is the critical angle for glass, and 45° is bigger.", "So the light is totally internally reflected."],
      },
      {
        id: "wv-mcq-q33",
        question: "Which colour of visible light has the shortest wavelength?",
        options: ["Red", "Green", "Yellow", "Violet"],
        answerIndex: 3,
        explanation: "Violet has the shortest wavelength (~400 nm) and highest frequency; red has the longest (~700 nm).",
        guideRef: "The electromagnetic spectrum",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q34",
        question: "Which is the correct order of visible colours from longest to shortest wavelength?",
        options: [
          "Violet, Blue, Green, Yellow, Orange, Red",
          "Red, Orange, Yellow, Green, Blue, Indigo, Violet",
          "Red, Yellow, Orange, Green, Indigo, Blue, Violet",
          "Green, Blue, Red, Yellow, Violet, Orange",
        ],
        answerIndex: 1,
        explanation: "From longest to shortest wavelength: Red, Orange, Yellow, Green, Blue, Indigo, Violet.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["Red is the longest wavelength.", "Violet is the shortest.", "Think of a rainbow from the outside (red) inwards."],
      },
      {
        id: "wv-mcq-q35",
        question: "Which type of EM radiation is ionising and used to sterilise medical equipment and treat cancer?",
        options: ["Radio waves", "Microwaves", "Infrared", "Gamma rays"],
        answerIndex: 3,
        explanation: "Gamma rays are ionising; they are used to sterilise equipment, to treat cancer (radiotherapy) and can also cause cancer if cells are damaged.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["Which end of the spectrum carries the most energy?", "Ionising radiation can knock electrons off atoms.", "It is the highest-frequency band."],
      },
      {
        id: "wv-mcq-q36",
        question: "Which is a danger of ultraviolet radiation?",
        options: ["It can cause skin cancer and eye damage", "It heats the water in food", "It is used for radio broadcasts", "It cannot affect living tissue"],
        answerIndex: 0,
        explanation: "UV damages skin cells (premature ageing and skin cancer) and can damage the eyes; that is why sunscreen and UV-blocking sunglasses are used.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q37",
        question: "Which EM band is used for cooking food and for satellite/mobile-phone communication?",
        options: ["Infrared", "Microwaves", "X-rays", "Ultraviolet"],
        answerIndex: 1,
        explanation: "Microwaves are absorbed by water in food (heating it) and pass easily through the atmosphere for satellite and mobile communication.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "warmup",
      },
      {
        id: "wv-mcq-q38",
        question: "An oscilloscope shows two sound traces. Trace B has the same height as Trace A but its waves are twice as close together. Compared with A, sound B is…",
        options: ["louder at the same pitch", "the same loudness but higher pitch", "quieter at a lower pitch", "identical"],
        answerIndex: 1,
        explanation: "Same height = same amplitude = same loudness. Waves closer together = higher frequency = higher pitch.",
        guideRef: "Sound waves",
        difficulty: "core",
        hints: ["Trace height shows amplitude (loudness).", "How close the waves are shows frequency (pitch).", "Same height, closer waves = ?"],
      },
      {
        id: "wv-mcq-q39",
        question: "A student measures the speed of sound by clapping 75 m from a wall and timing the echo at 0.44 s. The speed of sound is about…",
        options: ["170 m/s", "341 m/s", "33 m/s", "165 m/s"],
        answerIndex: 1,
        explanation: "The sound travels to the wall and back, a distance 2 × 75 = 150 m. v = distance/time = 150 / 0.44 ≈ 341 m/s.",
        guideRef: "Sound waves",
        difficulty: "challenge",
        hints: ["The sound travels to the wall AND back.", "Distance = 2 × 75 = 150 m.", "v = 150 ÷ 0.44 = ?"],
        strategy: "Remember the echo travels there and back (2d)",
      },
      {
        id: "wv-mcq-q40",
        question: "An object 4 cm tall produces an image 10 cm tall through a converging lens. The magnification is…",
        options: ["0.4", "2.5", "6", "40"],
        answerIndex: 1,
        explanation: "magnification = image height / object height = 10 / 4 = 2.5 (no unit).",
        guideRef: "Converging lenses and ray diagrams",
        difficulty: "core",
        hints: ["Which formula gives magnification?", "magnification = image height / object height.", "10 ÷ 4 = ?"],
        strategy: "Use magnification = image height / object height",
      },
      {
        id: "wv-mcq-q41",
        question: "Five complete water waves pass a post every 2 seconds. The frequency of the waves is…",
        options: ["0.4 Hz", "2.5 Hz", "5 Hz", "10 Hz"],
        answerIndex: 1,
        explanation: "Frequency = number of waves ÷ time = 5 ÷ 2 = 2.5 Hz.",
        guideRef: "Describing waves: amplitude, wavelength, frequency, period",
        difficulty: "core",
        hints: ["Frequency is waves per second.", "Divide the number of waves by the time.", "5 ÷ 2 = ?"],
      },
      {
        id: "wv-mcq-q42",
        question: "On the principal axis of a converging lens, the principal focus F is the point where…",
        options: ["the object must always be placed", "rays parallel to the axis are brought together after the lens", "the lens is thickest", "light is reflected"],
        answerIndex: 1,
        explanation: "Rays arriving parallel to the principal axis converge at the principal focus F; the lens-to-F distance is the focal length.",
        guideRef: "Converging lenses and ray diagrams",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "wv-qa-q01",
        question: "State the difference between a transverse and a longitudinal wave, giving one example of each. (3 marks)",
        marks: 3,
        modelAnswer:
          "In a transverse wave the vibrations are at right angles (90°) to the direction the wave travels, for example a water wave or light. In a longitudinal wave the vibrations are parallel to (along) the direction of travel, forming compressions and rarefactions, for example a sound wave.",
        markScheme: [
          "Transverse: vibrations at 90° / perpendicular to direction of travel",
          "Longitudinal: vibrations parallel to / along direction of travel",
          "One correct example of each (transverse: water | light | EM; longitudinal: sound | slinky push-pull)",
        ],
        commonError: "Mixing up the directions, or giving sound as a transverse wave.",
        guideRef: "What is a wave? Transverse vs longitudinal",
        difficulty: "core",
        hints: ["Compare vibration direction with travel direction.", "Which is 90° and which is parallel?", "Give a familiar example for each."],
      },
      {
        id: "wv-qa-q02",
        question: "Define amplitude, wavelength and frequency, including the unit of frequency. (3 marks)",
        marks: 3,
        modelAnswer:
          "Amplitude is the maximum displacement of a particle from its rest position. Wavelength is the distance of one complete wave, for example from one crest to the next. Frequency is the number of complete waves passing a point each second, measured in hertz (Hz).",
        markScheme: [
          "Amplitude = maximum displacement from rest position",
          "Wavelength = distance of one complete wave | crest to crest",
          "Frequency = number of waves per second, unit hertz / Hz",
        ],
        commonError: "Defining amplitude as the distance from crest to trough (that is double the amplitude).",
        guideRef: "Describing waves: amplitude, wavelength, frequency, period",
        difficulty: "core",
        hints: ["Amplitude is measured from the middle (rest) line.", "Wavelength is one full cycle.", "Frequency is a count per second — what unit?"],
      },
      {
        id: "wv-qa-q03",
        question: "A water wave has a frequency of 2.5 Hz and a wavelength of 0.80 m. Calculate the speed of the wave. (3 marks)",
        marks: 3,
        modelAnswer:
          "Using v = f λ: v = 2.5 × 0.80 = 2.0 m/s.",
        markScheme: [
          "Correct equation v = f λ stated or used",
          "Correct substitution 2.5 × 0.80",
          "v = 2.0 m/s with unit",
        ],
        commonError: "Forgetting the unit m/s, or dividing instead of multiplying.",
        guideRef: "The wave equation v = f λ",
        difficulty: "core",
        hints: ["Which equation links speed, frequency and wavelength?", "v = f λ.", "Multiply 2.5 by 0.80 and add the unit."],
        solutions: [
          {
            label: "Method: direct substitution into v = f λ",
            steps: [
              "Write the equation: v = f λ.",
              "List values: f = 2.5 Hz, λ = 0.80 m.",
              "Substitute: v = 2.5 × 0.80.",
              "Calculate: v = 2.0 m/s.",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q04",
        question: "A radio station broadcasts at a frequency of 1.0 × 10⁸ Hz. Radio waves travel at 3.0 × 10⁸ m/s. Calculate the wavelength of the waves. (3 marks)",
        marks: 3,
        modelAnswer:
          "Rearrange v = f λ to λ = v/f. λ = (3.0 × 10⁸)/(1.0 × 10⁸) = 3.0 m.",
        markScheme: [
          "Rearranged equation λ = v/f",
          "Correct substitution (3.0 × 10⁸) ÷ (1.0 × 10⁸)",
          "λ = 3.0 m with unit",
        ],
        commonError: "Multiplying v by f instead of dividing, or mishandling the powers of ten.",
        guideRef: "The wave equation v = f λ",
        difficulty: "core",
        hints: ["Make λ the subject of v = f λ.", "λ = v/f.", "Divide the two powers of ten: 3.0×10⁸ ÷ 1.0×10⁸."],
        solutions: [
          {
            label: "Method 1: rearrange then substitute",
            steps: [
              "Start from v = f λ.",
              "Rearrange: λ = v / f.",
              "Substitute: λ = (3.0 × 10⁸) / (1.0 × 10⁸).",
              "The powers of ten cancel: λ = 3.0 m.",
            ],
          },
          {
            label: "Method 2: substitute then solve",
            steps: [
              "Substitute into v = f λ: 3.0 × 10⁸ = (1.0 × 10⁸) × λ.",
              "Divide both sides by 1.0 × 10⁸.",
              "λ = (3.0 × 10⁸) / (1.0 × 10⁸) = 3.0 m.",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q05",
        question: "State the law of reflection. Explain what is meant by the 'normal' and why angles are measured from it. (3 marks)",
        marks: 3,
        modelAnswer:
          "The law of reflection states that the angle of incidence equals the angle of reflection. The normal is an imaginary line drawn at 90° (right angles) to the surface at the point where the ray hits. Angles are measured from the normal because the surface itself may be curved or angled, so the normal gives a fixed, consistent reference line.",
        markScheme: [
          "Angle of incidence = angle of reflection",
          "Normal = line at 90° to the surface at the point of incidence",
          "Angles measured from the normal (consistent reference) not the surface",
        ],
        commonError: "Saying angles are measured from the mirror surface.",
        guideRef: "Wavefronts, reflection and the law of reflection",
        difficulty: "core",
        hints: ["What is the relationship between i and r?", "Where is the normal drawn?", "Why not measure from the surface itself?"],
      },
      {
        id: "wv-qa-q06",
        question: "Explain, in terms of wave speed, why a ray of light bends towards the normal when it passes from air into glass. (3 marks)",
        marks: 3,
        modelAnswer:
          "Glass is optically denser than air, so light travels more slowly in glass. As the wavefront crosses the boundary at an angle, the part that enters the glass first slows down before the rest, so that side lags behind. This makes the wavefront pivot and the ray changes direction, bending towards the normal.",
        markScheme: [
          "Light slows down on entering the (denser) glass",
          "Change in speed causes change in direction (refraction)",
          "Ray bends towards the normal",
        ],
        commonError: "Saying light 'bends because the glass is denser' without mentioning the change in speed.",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["What happens to the speed of light entering glass?", "A change in speed at an angle causes what?", "Which way does it bend going into a denser medium?"],
      },
      {
        id: "wv-qa-q07",
        question: "A ray of light travels from air into a glass block. The angle of incidence is 60° and the angle of refraction is 35°. Calculate the refractive index of the glass. (Take sin 60° = 0.866, sin 35° = 0.574.) (3 marks)",
        marks: 3,
        modelAnswer:
          "n = sin i / sin r = sin 60° / sin 35° = 0.866 / 0.574 = 1.5 (to 2 s.f.).",
        markScheme: [
          "Equation n = sin i / sin r",
          "Correct substitution 0.866 / 0.574",
          "n = 1.5 (accept 1.51)",
        ],
        commonError: "Dividing the angles (60/35) instead of their sines, or putting sin r on top.",
        guideRef: "Refraction and refractive index",
        difficulty: "core",
        hints: ["Use n = sin i / sin r.", "Take the sine of each angle first.", "0.866 ÷ 0.574 = ?"],
        solutions: [
          {
            label: "Method 1: using n = sin i / sin r (angles given)",
            steps: [
              "Write n = sin i / sin r.",
              "sin 60° = 0.866, sin 35° = 0.574.",
              "n = 0.866 / 0.574 ≈ 1.5.",
            ],
          },
          {
            label: "Method 2: cross-check using speed",
            steps: [
              "n can also be found from n = c/v.",
              "With n = 1.5 and c = 3.0 × 10⁸ m/s, the expected speed in glass is v = c/n.",
              "v = (3.0 × 10⁸)/1.5 = 2.0 × 10⁸ m/s — a sensible value, confirming n ≈ 1.5.",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q08",
        question: "Describe how an optical fibre uses total internal reflection to carry a light signal. State the two conditions needed for total internal reflection. (4 marks)",
        marks: 4,
        modelAnswer:
          "Light enters one end of the thin glass core and travels along it. Each time the light hits the boundary between the core and the outside it strikes at an angle greater than the critical angle, so it is totally internally reflected back into the core. The light therefore zig-zags down the fibre with almost no energy lost, carrying the signal to the far end. The two conditions for total internal reflection are: (1) the light must be travelling from a denser medium to a less dense one, and (2) the angle of incidence must be greater than the critical angle.",
        markScheme: [
          "Light hits the core boundary at an angle greater than the critical angle",
          "It is totally internally reflected (repeatedly) and stays inside the core",
          "Condition 1: travelling from denser to less dense medium",
          "Condition 2: angle of incidence greater than the critical angle",
        ],
        commonError: "Saying the light is 'refracted' down the fibre — it is reflected; and forgetting the denser→less dense condition.",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "core",
        hints: ["How does the light stay inside the core?", "What must the angle of incidence be compared with the critical angle?", "Don't forget the denser→less dense condition."],
      },
      {
        id: "wv-qa-q09",
        question: "A type of glass has a refractive index of 1.5. Calculate its critical angle. (Take the angle whose sine is 0.667 to be 42°.) (3 marks)",
        marks: 3,
        modelAnswer:
          "Using sin c = 1/n: sin c = 1/1.5 = 0.667, so c = 42°.",
        markScheme: [
          "Equation sin c = 1/n",
          "sin c = 1/1.5 = 0.667",
          "c = 42°",
        ],
        commonError: "Using sin c = n instead of sin c = 1/n, giving an impossible value greater than 1.",
        guideRef: "Total internal reflection and the critical angle",
        difficulty: "core",
        hints: ["Which equation gives the critical angle?", "sin c = 1/n.", "1 ÷ 1.5 = 0.667, then take the inverse sine."],
        solutions: [
          {
            label: "Method: using sin c = 1/n",
            steps: [
              "Write sin c = 1/n.",
              "Substitute n = 1.5: sin c = 1/1.5 = 0.667.",
              "Take the inverse sine: c = 42°.",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q10",
        question: "Name the seven regions of the electromagnetic spectrum in order from longest to shortest wavelength, and give one use of microwaves and one danger of ultraviolet radiation. (5 marks)",
        marks: 5,
        modelAnswer:
          "From longest to shortest wavelength the regions are: radio waves, microwaves, infrared, visible light, ultraviolet, X-rays and gamma rays. A use of microwaves is satellite or mobile-phone communication (or cooking). A danger of ultraviolet radiation is that it can damage skin cells, causing premature ageing and skin cancer, and can damage the eyes.",
        markScheme: [
          "Correct order: Radio, Microwave, Infrared, Visible, UV, X-ray, Gamma",
          "All seven named correctly",
          "One correct use of microwaves: communication | satellites | mobile phones | cooking",
          "One correct danger of UV: skin damage | skin cancer | eye damage",
          "Order and identification clear enough to credit",
        ],
        commonError: "Swapping the order of microwaves and infrared, or putting UV after X-rays.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["Radio is longest; gamma is shortest.", "Microwave then infrared come after radio.", "UV harms which part of the body?"],
      },
      {
        id: "wv-qa-q11",
        question: "Explain why sound can travel through water but not through the vacuum of space. Refer to the nature of a sound wave in your answer. (3 marks)",
        marks: 3,
        modelAnswer:
          "Sound is a longitudinal wave that travels as compressions and rarefactions of particles, so it needs a medium with particles to pass the vibrations along. Water contains particles (molecules) that can be squashed and stretched, so sound travels through it. Space is a vacuum with virtually no particles, so there is nothing to carry the vibrations and sound cannot travel through it.",
        markScheme: [
          "Sound is longitudinal / travels by compressions and rarefactions of particles",
          "It needs a medium (particles) to travel",
          "Water has particles to carry it; a vacuum has none, so no sound",
        ],
        commonError: "Saying sound 'is too weak' in space rather than that there is no medium.",
        guideRef: "Sound waves",
        difficulty: "core",
        hints: ["What does a sound wave need to pass the vibration on?", "Does space have particles?", "Link 'no medium' to 'no sound'."],
      },
      {
        id: "wv-qa-q12",
        question: "A bat emits an ultrasound pulse at a frequency of 50 000 Hz. The speed of sound in air is 340 m/s. (a) Calculate the wavelength of the pulse. (b) Explain why humans cannot hear this sound. (4 marks)",
        marks: 4,
        modelAnswer:
          "(a) Rearrange v = f λ to λ = v/f = 340 / 50 000 = 0.0068 m (6.8 mm). (b) The frequency is 50 000 Hz, which is above the upper limit of human hearing (about 20 000 Hz), so it is ultrasound and a human ear cannot detect it.",
        markScheme: [
          "Rearrangement λ = v/f",
          "λ = 340 / 50 000 = 0.0068 m (accept 6.8 mm)",
          "Human hearing range upper limit is about 20 000 Hz",
          "50 000 Hz is above this (ultrasound), so cannot be heard",
        ],
        commonError: "Giving the wavelength without a unit; or quoting the human range incorrectly.",
        guideRef: "Sound waves",
        difficulty: "challenge",
        hints: ["Part (a): make λ the subject of v = f λ.", "λ = v/f = 340 ÷ 50 000.", "Part (b): compare 50 000 Hz with the top of the human range (20 000 Hz)."],
        solutions: [
          {
            label: "Part (a): rearrange v = f λ",
            steps: [
              "Start from v = f λ and rearrange: λ = v / f.",
              "Substitute: λ = 340 / 50 000.",
              "Calculate: λ = 0.0068 m, i.e. 6.8 mm.",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q13",
        question: "An object is placed in front of a converging lens, beyond the principal focus F. Describe how to locate the image using a ray diagram, and state two properties of the image formed. (5 marks)",
        marks: 5,
        modelAnswer:
          "From the top of the object draw two rays. First draw a ray parallel to the principal axis; after passing through the lens it refracts so that it goes through the principal focus F on the far side. Second draw a ray that goes straight through the centre of the lens, which continues without bending. The point where these two rays cross is the top of the image; the image stands from the axis to that point. Because the object is beyond F the rays actually cross, so the image is real and inverted (and, if the object is beyond 2F, it is also smaller than the object). Two properties: the image is real and inverted.",
        markScheme: [
          "Ray 1: parallel to axis then refracts through the focal point F",
          "Ray 2: straight through the centre of the lens, undeviated",
          "Image is located where the two rays cross",
          "Property: real (rays actually cross / can be put on a screen)",
          "Property: inverted (upside down)",
        ],
        commonError: "Drawing the parallel ray passing through F on the same side as the object, or forgetting the straight-through-centre ray.",
        guideRef: "Converging lenses and ray diagrams",
        difficulty: "challenge",
        hints: ["What does the parallel ray do after the lens?", "Which ray passes straight through undeviated?", "Where the rays cross is the image — real or virtual here?"],
      },
      {
        id: "wv-qa-q14",
        question: "A period of one wave on an oscilloscope is measured as 0.004 s. (a) Calculate the frequency of the sound. (b) State whether a human could hear it, giving a reason. (4 marks)",
        marks: 4,
        modelAnswer:
          "(a) f = 1/T = 1/0.004 = 250 Hz. (b) Yes — 250 Hz lies within the human hearing range of about 20 Hz to 20 000 Hz, so it can be heard.",
        markScheme: [
          "Equation f = 1/T used",
          "f = 1/0.004 = 250 Hz",
          "Compares 250 Hz with the human range (20 Hz – 20 000 Hz)",
          "Concludes it can be heard (it is inside the range)",
        ],
        commonError: "Forgetting to convert period to frequency, or quoting the hearing range wrongly.",
        guideRef: "Sound waves",
        difficulty: "core",
        hints: ["Part (a): which equation links f and T?", "f = 1/T = 1 ÷ 0.004.", "Part (b): is 250 Hz between 20 and 20 000 Hz?"],
        solutions: [
          {
            label: "Method: f = 1/T then compare to the audible range",
            steps: [
              "Write f = 1/T.",
              "Substitute: f = 1 / 0.004 = 250 Hz.",
              "Compare with the audible range 20 Hz – 20 000 Hz.",
              "250 Hz is inside the range, so it can be heard.",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q15",
        question: "Describe a method to measure the speed of sound in air using an echo, and give the equation you would use. (4 marks)",
        marks: 4,
        modelAnswer:
          "Stand a measured distance d from a large flat wall (e.g. 50 m). Clap your hands and use a stopwatch to time how long t it takes to hear the echo. The sound travels to the wall and back, a distance of 2d. The speed is v = 2d / t. Repeating several times and taking an average reduces the timing error.",
        markScheme: [
          "Measure a distance d to a large flat reflecting surface (wall)",
          "Make a sound (clap) and time the echo with a stopwatch",
          "Recognise the sound travels there and back, distance 2d",
          "v = 2d / t (and/or repeat and average to improve accuracy)",
        ],
        commonError: "Using distance d instead of 2d, forgetting the sound makes a round trip to the wall and back.",
        guideRef: "Sound waves",
        difficulty: "core",
        hints: ["You need a distance and a time.", "Time the echo from a wall a known distance away.", "The sound goes there and back, so distance = 2d."],
      },
      {
        id: "wv-qa-q16",
        question: "Compare two sounds shown on an oscilloscope: sound X has a taller, more spread-out trace; sound Y has a shorter, more bunched-up trace. Describe how each sound differs in loudness and pitch. (4 marks)",
        marks: 4,
        modelAnswer:
          "The height of a trace shows the amplitude and the spacing of the waves shows the frequency. Sound X has a taller trace, so it has a larger amplitude and is louder; its waves are spread out, so it has a lower frequency and a lower pitch. Sound Y has a shorter trace, so a smaller amplitude and is quieter; its waves are bunched up, so it has a higher frequency and a higher pitch.",
        markScheme: [
          "Taller trace = larger amplitude = louder (X louder than Y)",
          "Spread-out waves = lower frequency = lower pitch (X lower pitch)",
          "Shorter trace = smaller amplitude = quieter (Y quieter)",
          "Bunched-up waves = higher frequency = higher pitch (Y higher pitch)",
        ],
        commonError: "Linking amplitude to pitch or frequency to loudness — they are swapped.",
        guideRef: "Sound waves",
        difficulty: "core",
        hints: ["Trace height tells you amplitude.", "Wave spacing tells you frequency.", "Amplitude → loudness; frequency → pitch."],
      },
      {
        id: "wv-qa-q17",
        question: "An object 5 mm tall is viewed through a magnifying glass, producing an upright virtual image 15 mm tall. (a) Calculate the magnification. (b) State two properties of the image and where the object must be placed. (4 marks)",
        marks: 4,
        modelAnswer:
          "(a) magnification = image height / object height = 15 / 5 = 3 (no unit). (b) The image is virtual and upright (and magnified). The object must be placed inside the focal length F (between the lens and F).",
        markScheme: [
          "Equation magnification = image height / object height",
          "magnification = 15 / 5 = 3 (no unit)",
          "Image is virtual and upright (accept magnified)",
          "Object placed inside the focal length / between the lens and F",
        ],
        commonError: "Adding a unit to magnification, or saying the image is real (a magnifying glass forms a virtual image).",
        guideRef: "Converging lenses and ray diagrams",
        difficulty: "core",
        hints: ["Part (a): divide image height by object height.", "15 ÷ 5 = ? (no unit).", "Part (b): a magnifying glass gives a virtual, upright image; the object sits inside F."],
        solutions: [
          {
            label: "Method: magnification = image height / object height",
            steps: [
              "Write magnification = image height / object height.",
              "Substitute: magnification = 15 / 5.",
              "Calculate: magnification = 3 (a ratio, no unit).",
            ],
          },
        ],
      },
      {
        id: "wv-qa-q18",
        question: "For X-rays and for infrared radiation, give one use and one danger of each. (4 marks)",
        marks: 4,
        modelAnswer:
          "X-rays: a use is producing medical images of bones (or airport security scanning); a danger is that they are ionising and can damage cells and cause cancer. Infrared: a use is in remote controls, thermal imaging or heaters/grills; a danger is that it can burn the skin (overheating of body tissue).",
        markScheme: [
          "One correct use of X-rays: imaging bones | medical X-ray | airport security",
          "One correct danger of X-rays: ionising | damages cells | causes cancer",
          "One correct use of infrared: remote controls | thermal imaging | heaters | optical fibre signals",
          "One correct danger of infrared: skin burns | overheating tissue",
        ],
        commonError: "Giving infrared as ionising — it is not; the ionising bands are X-ray and gamma.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["X-rays pass through soft tissue but not bone.", "X-rays and gamma are ionising.", "Infrared is felt as heat."],
      },
      {
        id: "wv-qa-q19",
        question: "Explain how a ripple tank can be used to show that water waves slow down and change wavelength when they move into shallower water. (4 marks)",
        marks: 4,
        modelAnswer:
          "Set up a ripple tank with a vibrating bar making straight wavefronts at a fixed frequency, and place a flat glass plate in part of the tank so the water there is shallower. A lamp above projects the wavefronts onto a screen below. Over the shallow region the waves travel more slowly. Because the frequency is fixed by the bar, the wave equation v = f λ means a smaller speed gives a shorter wavelength, so the projected wavefronts are seen to be closer together over the shallow water. If the waves cross the boundary at an angle, the change in speed also changes their direction (refraction).",
        markScheme: [
          "Vibrating bar makes wavefronts at a fixed frequency; lamp projects them onto a screen",
          "A glass plate makes the water shallower so the waves slow down",
          "Frequency stays constant, so by v = f λ the wavelength decreases",
          "Wavefronts seen closer together (and direction changes if at an angle = refraction)",
        ],
        commonError: "Saying the frequency changes — it is fixed by the dipper; it is the speed and wavelength that change.",
        guideRef: "Wavefronts, the ripple tank, reflection and the law of reflection",
        difficulty: "challenge",
        hints: ["What fixes the frequency of the waves?", "A glass plate makes the water shallower, slowing the waves.", "With f fixed, v = f λ tells you what happens to λ."],
      },
      {
        id: "wv-qa-q20",
        question: "White light is passed through a triangular prism and splits into a spectrum. Name the colours in order from the longest wavelength to the shortest, and state which colour is refracted (bent) the most. (4 marks)",
        marks: 4,
        modelAnswer:
          "In order of decreasing wavelength the colours are red, orange, yellow, green, blue, indigo and violet. Violet (the shortest wavelength) is refracted, or bent, the most; red (the longest wavelength) is bent the least.",
        markScheme: [
          "Order: Red, Orange, Yellow, Green, Blue, Indigo, Violet",
          "Red identified as longest wavelength",
          "Violet identified as shortest wavelength",
          "Violet is refracted/bent the most (red the least)",
        ],
        commonError: "Reversing the order, or saying red bends the most.",
        guideRef: "The electromagnetic spectrum",
        difficulty: "core",
        hints: ["Red is at the long-wavelength end.", "Violet is at the short-wavelength end.", "Shorter wavelength light is refracted more."],
      },
    ],
  },
  // questionBank omitted — auto-assembled from the quiz pools by lib/content.ts.
};
