import type { Topic } from "../types";

// STUB — full content generated by the content pipeline. Valid and buildable.
export const wv: Topic = {
  id: "wv",
  code: "WV",
  number: 2,
  title: "Waves",
  subject: "Physics",
  icon: "🌊",
  color: "#06b6d4",
  intro: "Waves carry energy without carrying matter. Discover how sound and light travel, reflect, refract and spread out, and meet the whole electromagnetic spectrum.",
  guide: [
    {
      heading: "Coming soon",
      body: "Full revision content for this topic is being prepared.",
      keyPoints: ["Content in progress"],
    },
  ],
  learn: {
    bigIdea: "Waves carry energy without carrying matter. Discover how sound and light travel, reflect, refract and spread out, and meet the whole electromagnetic spectrum.",
    mustKnow: ["Content in progress"],
    keywords: [{ term: "Waves", definition: "Waves carry energy without carrying matter. Discover how sound and light travel, reflect, refract and spread out, and meet the whole electromagnetic spectrum." }],
    flashcards: [],
  },
  quiz: {
    mcq: [
      {
        id: "wv-mcq-q01",
        question: "Placeholder question for Waves — content coming soon.",
        options: ["A", "B", "C", "D"],
        answerIndex: 0,
        explanation: "Placeholder.",
        difficulty: "warmup",
      },
    ],
    qa: [
      {
        id: "wv-qa-q01",
        question: "Placeholder exam question for Waves. (1 mark)",
        marks: 1,
        modelAnswer: "Placeholder model answer.",
        markScheme: ["Placeholder"],
        difficulty: "core",
      },
    ],
  },
};
